/*========================================================================
 * cr3bp_stt_time_derivatives_gen.c
 *
 * AUTO-GENERATED by generate_cr3bp_stt.py — DO NOT EDIT
 *
 * Optimized pure-C implementation of higher-order time derivatives
 * for the CR3BP state, STM, and 2nd-4th order State Transition Tensors.
 *
 * Key optimizations vs. the generic C++ version:
 *   - No heap allocations (fixed-size stack/static arrays)
 *   - Compact tensor storage (only nonzero B/C/D entries)
 *   - Sparsity-exploiting variational equation loops (p,q,r,s < 3)
 *   - Precomputed product tree eliminates 5-fold convolution for D
 *
 * API matches cr3bp_stt_time_derivatives.h
 * Compile: mex -O cr3bp_stt_time_derivatives_mex.c cr3bp_stt_time_derivatives_gen.c
 *========================================================================*/

#include "cr3bp_stt_time_derivatives.h"
#include <math.h>
#include <string.h>

/* Maximum Taylor coefficients */
#define KP1 (CR3BP_NMAX + 1)  /* 13 */

/* Tensor block sizes */
#define SZ1  36
#define SZ2  216
#define SZ3  1296
#define SZ4  7776

/* Index helpers (0-based, column-major) */
#define IDX2(i,a) ((i) + 6*(a))
#define IDX3(i,a,b) ((i) + 6*((a) + 6*(b)))
#define IDX4(i,a,b,c) ((i) + 6*((a) + 6*((b) + 6*(c))))
#define IDX5(i,a,b,c,d) ((i) + 6*((a) + 6*((b) + 6*((c) + 6*(d)))))

/* Factorial table */
static const double FACT[14] = {1.0, 1.0, 2.0, 6.0, 24.0, 120.0, 720.0, 5040.0, 40320.0, 362880.0, 3628800.0, 39916800.0, 479001600.0, 6227020800.0};

/* Lookup: any 2-tuple from {0,1,2}^2 -> sorted flat index (0..5) */
/* Encoding: t[0] + 3*t[1] + 9*t[2] + ... */
static const int PAIR_LUT[9] = {0, 1, 2, 1, 3, 4, 2, 4, 5};

/* Lookup: any 3-tuple from {0,1,2}^3 -> sorted flat index (0..9) */
/* Encoding: t[0] + 3*t[1] + 9*t[2] + ... */
static const int TRIPLE_LUT[27] = {0, 1, 2, 1, 3, 4, 2, 4, 5, 1, 3, 4, 3, 6, 7, 4, 7, 8, 2, 4, 5, 4, 7, 8, 5, 8, 9};

/* Lookup: any 4-tuple from {0,1,2}^4 -> sorted flat index (0..14) */
/* Encoding: t[0] + 3*t[1] + 9*t[2] + ... */
static const int QUAD_LUT[81] = {0, 1, 2, 1, 3, 4, 2, 4, 5, 1, 3, 4, 3, 6, 7, 4, 7, 8, 2, 4, 5, 4, 7, 8, 5, 8, 9, 1, 3, 4, 3, 6, 7, 4, 7, 8, 3, 6, 7, 6, 10, 11, 7, 11, 12, 4, 7, 8, 7, 11, 12, 8, 12, 13, 2, 4, 5, 4, 7, 8, 5, 8, 9, 4, 7, 8, 7, 11, 12, 8, 12, 13, 5, 8, 9, 8, 12, 13, 9, 13, 14};

/* Lookup: any 5-tuple from {0,1,2}^5 -> sorted flat index (0..20) */
/* Encoding: t[0] + 3*t[1] + 9*t[2] + ... */
static const int QUINT_LUT[243] = {0, 1, 2, 1, 3, 4, 2, 4, 5, 1, 3, 4, 3, 6, 7, 4, 7, 8, 2, 4, 5, 4, 7, 8, 5, 8, 9, 1, 3, 4, 3, 6, 7, 4, 7, 8, 3, 6, 7, 6, 10, 11, 7, 11, 12, 4, 7, 8, 7, 11, 12, 8, 12, 13, 2, 4, 5, 4, 7, 8, 5, 8, 9, 4, 7, 8, 7, 11, 12, 8, 12, 13, 5, 8, 9, 8, 12, 13, 9, 13, 14, 1, 3, 4, 3, 6, 7, 4, 7, 8, 3, 6, 7, 6, 10, 11, 7, 11, 12, 4, 7, 8, 7, 11, 12, 8, 12, 13, 3, 6, 7, 6, 10, 11, 7, 11, 12, 6, 10, 11, 10, 15, 16, 11, 16, 17, 7, 11, 12, 11, 16, 17, 12, 17, 18, 4, 7, 8, 7, 11, 12, 8, 12, 13, 7, 11, 12, 11, 16, 17, 12, 17, 18, 8, 12, 13, 12, 17, 18, 13, 18, 19, 2, 4, 5, 4, 7, 8, 5, 8, 9, 4, 7, 8, 7, 11, 12, 8, 12, 13, 5, 8, 9, 8, 12, 13, 9, 13, 14, 4, 7, 8, 7, 11, 12, 8, 12, 13, 7, 11, 12, 11, 16, 17, 12, 17, 18, 8, 12, 13, 12, 17, 18, 13, 18, 19, 5, 8, 9, 8, 12, 13, 9, 13, 14, 8, 12, 13, 12, 17, 18, 13, 18, 19, 9, 13, 14, 13, 18, 19, 14, 19, 20};

/* Sorted-tuple index lookups */
#define PIDX(a,b) PAIR_LUT[(a) + 3*(b)]
#define TIDX(a,b,c) TRIPLE_LUT[(a) + 3*(b) + 9*(c)]
#define QIDX(a,b,c,d) QUAD_LUT[(a) + 3*(b) + 9*(c) + 27*(d)]
#define UIDX(a,b,c,d,e) QUINT_LUT[(a) + 3*(b) + 9*(c) + 27*(d) + 81*(e)]

/* Cauchy product: result[k] = sum_{j=0}^{k} a[j]*b[k-j] for k=0..K */
static void cprod(double *result, const double *a, const double *b, int K)
{
    int kk, jj;
    for (kk = 0; kk <= K; kk++) {
        double s = 0.0;
        for (jj = 0; jj <= kk; jj++)
            s += a[jj] * b[kk - jj];
        result[kk] = s;
    }
}

/* Power recurrence: result = s^alpha as Taylor coefficients */
static void power_rec(double *result, const double *s, double alpha, int K)
{
    int kk, jj;
    double inv0 = 1.0 / s[0];
    result[0] = pow(s[0], alpha);
    for (kk = 1; kk <= K; kk++) {
        double sum = 0.0;
        for (jj = 0; jj < kk; jj++)
            sum += (alpha * (kk - jj) - jj) * s[kk - jj] * result[jj];
        result[kk] = inv0 * sum / (double)kk;
    }
}

int compute_cr3bp_stt_taylor_coefficients(
    const double *X0,
    const double *Phi1_0,
    const double *Phi2_0,
    const double *Phi3_0,
    const double *Phi4_0,
    double mu,
    int N,
    double *Xders,
    double *Phi1ders,
    double *Phi2ders,
    double *Phi3ders,
    double *Phi4ders)
{
    int k, j, j1, j2, j3, j4;
    int a, b, c, d, alpha, beta, gamma, delta, eps;
    int p, q, r, ss, i_row;
    double inv_kp1, rhs, mu1;

    if (N < 0 || N > CR3BP_NMAX)
        return -1;

    mu1 = 1.0 - mu;

    /* ================================================================
     * ARRAY DECLARATIONS
     * ================================================================ */

    /* State Taylor coefficients */
    double xc[KP1], yc[KP1], zc[KP1];
    double vxc[KP1], vyc[KP1], vzc[KP1];

    /* Shifted coordinates: q1 = x + mu, q2 = x - 1 + mu */
    double q1c[KP1], q2c[KP1];

    /* Squared terms */
    double y2[KP1], z2[KP1], q12[KP1], q22[KP1];

    /* Squared distances: s1 = q1^2+y^2+z^2, s2 = q2^2+y^2+z^2 */
    double s1[KP1], s2[KP1];

    /* Inverse power scalars: s^alpha */
    double g1[KP1], g2[KP1];
    double h1[KP1], h2[KP1];
    double e1[KP1], e2[KP1];
    double f1[KP1], f2[KP1];
    double w1[KP1], w2[KP1];

    /* Coordinate x g products (for acceleration, built incrementally) */
    double q1g1[KP1], yg1[KP1], zg1[KP1];
    double q2g2[KP1], yg2[KP1], zg2[KP1];

    /* Coordinate product x inverse-power Taylor series */
    /* Indexed: [body][flat_tuple_index][taylor_order] */
    double ch[2][3][KP1];  /* 1-coord x h (3 tuples, for A,B) */
    double cch[2][6][KP1];  /* 2-coord x h (6 tuples, for A) */
    double ce[2][3][KP1];  /* 1-coord x e (3 tuples, for B,C,D) */
    double cce[2][6][KP1];  /* 2-coord x e (6 tuples, for B,C) */
    double ccce[2][10][KP1];  /* 3-coord x e (10 tuples, for B) */
    double cf[2][3][KP1];  /* 1-coord x f (3 tuples, for C,D) */
    double ccf[2][6][KP1];  /* 2-coord x f (6 tuples, for C,D) */
    double cccf[2][10][KP1];  /* 3-coord x f (10 tuples, for C,D) */
    double ccccf[2][15][KP1];  /* 4-coord x f (15 tuples, for C) */
    double cw[2][3][KP1];  /* 1-coord x w (3 tuples, for D) */
    double ccw[2][6][KP1];  /* 2-coord x w (6 tuples, for D) */
    double cccw[2][10][KP1];  /* 3-coord x w (10 tuples, for D) */
    double ccccw[2][15][KP1];  /* 4-coord x w (15 tuples, for D) */
    double cccccw[2][21][KP1];  /* 5-coord x w (21 tuples, for D) */

    /* A tensor: time-varying entries A(3+alpha, beta) for alpha,beta in {0,1,2} */
    double Atv[3][3][KP1];

    /* B tensor: B(3+alpha, beta, gamma) compact, 27 entries per Taylor order */
    double Bc[27][KP1];  /* Bc[alpha*9 + beta*3 + gamma][k] */

    /* C tensor: C(3+alpha, beta, gamma, delta) compact, 81 entries */
    double Cc[81][KP1];  /* Cc[alpha*27 + beta*9 + gamma*3 + delta][k] */

    /* D tensor: D(3+alpha, beta, gamma, delta, eps) compact, 243 entries */
    double Dc[243][KP1];

    /* Phi Taylor coefficient arrays (static: ~970 KB total) */
    static double P1c[SZ1 * KP1];
    static double P2c[SZ2 * KP1];
    static double P3c[SZ3 * KP1];
    static double P4c[SZ4 * KP1];

    /* ================================================================
     * PHASE 1: Build state Taylor coefficients (incremental)
     * ================================================================ */

    /* Initial conditions */
    xc[0]  = X0[0]; yc[0]  = X0[1]; zc[0]  = X0[2];
    vxc[0] = X0[3]; vyc[0] = X0[4]; vzc[0] = X0[5];

    /* Build intermediates at k=0 */
    q1c[0] = xc[0] + mu;
    q2c[0] = xc[0] - 1.0 + mu;
    y2[0]  = yc[0] * yc[0];
    z2[0]  = zc[0] * zc[0];
    q12[0] = q1c[0] * q1c[0];
    q22[0] = q2c[0] * q2c[0];
    s1[0]  = q12[0] + y2[0] + z2[0];
    s2[0]  = q22[0] + y2[0] + z2[0];

    g1[0] = pow(s1[0], -1.5);
    g2[0] = pow(s2[0], -1.5);
    h1[0] = pow(s1[0], -2.5);
    h2[0] = pow(s2[0], -2.5);
    e1[0] = pow(s1[0], -3.5);
    e2[0] = pow(s2[0], -3.5);
    f1[0] = pow(s1[0], -4.5);
    f2[0] = pow(s2[0], -4.5);
    w1[0] = pow(s1[0], -5.5);
    w2[0] = pow(s2[0], -5.5);

    q1g1[0] = q1c[0] * g1[0];  q2g2[0] = q2c[0] * g2[0];
    yg1[0]  = yc[0]  * g1[0];  yg2[0]  = yc[0]  * g2[0];
    zg1[0]  = zc[0]  * g1[0];  zg2[0]  = zc[0]  * g2[0];

    for (k = 0; k < N; k++) {
        double axk, ayk, azk;

        /* Acceleration Taylor coefficients at order k */
        axk = 2.0*vyc[k] + xc[k] - mu1*q1g1[k] - mu*q2g2[k];
        ayk = -2.0*vxc[k] + yc[k] - mu1*yg1[k] - mu*yg2[k];
        azk = -mu1*zg1[k] - mu*zg2[k];

        /* Advance state to order k+1 */
        inv_kp1 = 1.0 / (double)(k + 1);
        xc[k+1]  = vxc[k] * inv_kp1;
        yc[k+1]  = vyc[k] * inv_kp1;
        zc[k+1]  = vzc[k] * inv_kp1;
        vxc[k+1] = axk * inv_kp1;
        vyc[k+1] = ayk * inv_kp1;
        vzc[k+1] = azk * inv_kp1;

        /* Build intermediates at order k+1 */
        q1c[k+1] = xc[k+1];  /* shift is only at k=0 */
        q2c[k+1] = xc[k+1];

        /* Squares via Cauchy product */
        { double sy2=0, sz2=0, sq12=0, sq22=0;
          int jj;
          for (jj = 0; jj <= k+1; jj++) {
              sy2  += yc[jj]  * yc[k+1-jj];
              sz2  += zc[jj]  * zc[k+1-jj];
              sq12 += q1c[jj] * q1c[k+1-jj];
              sq22 += q2c[jj] * q2c[k+1-jj];
          }
          y2[k+1]  = sy2;  z2[k+1]  = sz2;
          q12[k+1] = sq12; q22[k+1] = sq22;
        }
        s1[k+1] = q12[k+1] + y2[k+1] + z2[k+1];
        s2[k+1] = q22[k+1] + y2[k+1] + z2[k+1];

        /* Power recurrence at k+1 */
        { double inv0_1 = 1.0 / s1[0], inv0_2 = 1.0 / s2[0];
          int kk = k + 1, jj;
          { double sum1=0, sum2=0;
            for (jj = 0; jj < kk; jj++) {
                double w = -1.5 * (kk - jj) - jj;
                sum1 += w * s1[kk-jj] * g1[jj];
                sum2 += w * s2[kk-jj] * g2[jj];
            }
            g1[kk] = inv0_1 * sum1 / (double)kk;
            g2[kk] = inv0_2 * sum2 / (double)kk;
          }
          { double sum1=0, sum2=0;
            for (jj = 0; jj < kk; jj++) {
                double w = -2.5 * (kk - jj) - jj;
                sum1 += w * s1[kk-jj] * h1[jj];
                sum2 += w * s2[kk-jj] * h2[jj];
            }
            h1[kk] = inv0_1 * sum1 / (double)kk;
            h2[kk] = inv0_2 * sum2 / (double)kk;
          }
          { double sum1=0, sum2=0;
            for (jj = 0; jj < kk; jj++) {
                double w = -3.5 * (kk - jj) - jj;
                sum1 += w * s1[kk-jj] * e1[jj];
                sum2 += w * s2[kk-jj] * e2[jj];
            }
            e1[kk] = inv0_1 * sum1 / (double)kk;
            e2[kk] = inv0_2 * sum2 / (double)kk;
          }
          { double sum1=0, sum2=0;
            for (jj = 0; jj < kk; jj++) {
                double w = -4.5 * (kk - jj) - jj;
                sum1 += w * s1[kk-jj] * f1[jj];
                sum2 += w * s2[kk-jj] * f2[jj];
            }
            f1[kk] = inv0_1 * sum1 / (double)kk;
            f2[kk] = inv0_2 * sum2 / (double)kk;
          }
          { double sum1=0, sum2=0;
            for (jj = 0; jj < kk; jj++) {
                double w = -5.5 * (kk - jj) - jj;
                sum1 += w * s1[kk-jj] * w1[jj];
                sum2 += w * s2[kk-jj] * w2[jj];
            }
            w1[kk] = inv0_1 * sum1 / (double)kk;
            w2[kk] = inv0_2 * sum2 / (double)kk;
          }
        }

        /* coord*g products at k+1 */
        { double sq1g1=0, sq2g2=0, syg1=0, syg2=0, szg1=0, szg2=0;
          int jj;
          for (jj = 0; jj <= k+1; jj++) {
              sq1g1 += q1c[jj] * g1[k+1-jj];
              sq2g2 += q2c[jj] * g2[k+1-jj];
              syg1  += yc[jj]  * g1[k+1-jj];
              syg2  += yc[jj]  * g2[k+1-jj];
              szg1  += zc[jj]  * g1[k+1-jj];
              szg2  += zc[jj]  * g2[k+1-jj];
          }
          q1g1[k+1] = sq1g1; q2g2[k+1] = sq2g2;
          yg1[k+1]  = syg1;  yg2[k+1]  = syg2;
          zg1[k+1]  = szg1;  zg2[k+1]  = szg2;
        }
    } /* end state build loop */

    /* ================================================================
     * PHASE 2: Build coordinate-product Taylor series tree
     * ================================================================ */

    /* 1-coord x h products (3 per body) */
    cprod(ch[0][0], q1c, h1, N);
    cprod(ch[1][0], q2c, h2, N);
    cprod(ch[0][1], yc, h1, N);
    cprod(ch[1][1], yc, h2, N);
    cprod(ch[0][2], zc, h1, N);
    cprod(ch[1][2], zc, h2, N);

    /* 2-coord x h products (6 per body) */
    cprod(cch[0][0], q1c, ch[0][0], N);
    cprod(cch[1][0], q2c, ch[1][0], N);
    cprod(cch[0][1], q1c, ch[0][1], N);
    cprod(cch[1][1], q2c, ch[1][1], N);
    cprod(cch[0][2], q1c, ch[0][2], N);
    cprod(cch[1][2], q2c, ch[1][2], N);
    cprod(cch[0][3], yc, ch[0][1], N);
    cprod(cch[1][3], yc, ch[1][1], N);
    cprod(cch[0][4], yc, ch[0][2], N);
    cprod(cch[1][4], yc, ch[1][2], N);
    cprod(cch[0][5], zc, ch[0][2], N);
    cprod(cch[1][5], zc, ch[1][2], N);

    /* 1-coord x e products (3 per body) */
    cprod(ce[0][0], q1c, e1, N);
    cprod(ce[1][0], q2c, e2, N);
    cprod(ce[0][1], yc, e1, N);
    cprod(ce[1][1], yc, e2, N);
    cprod(ce[0][2], zc, e1, N);
    cprod(ce[1][2], zc, e2, N);

    /* 2-coord x e products (6 per body) */
    cprod(cce[0][0], q1c, ce[0][0], N);
    cprod(cce[1][0], q2c, ce[1][0], N);
    cprod(cce[0][1], q1c, ce[0][1], N);
    cprod(cce[1][1], q2c, ce[1][1], N);
    cprod(cce[0][2], q1c, ce[0][2], N);
    cprod(cce[1][2], q2c, ce[1][2], N);
    cprod(cce[0][3], yc, ce[0][1], N);
    cprod(cce[1][3], yc, ce[1][1], N);
    cprod(cce[0][4], yc, ce[0][2], N);
    cprod(cce[1][4], yc, ce[1][2], N);
    cprod(cce[0][5], zc, ce[0][2], N);
    cprod(cce[1][5], zc, ce[1][2], N);

    /* 3-coord x e products (10 per body) */
    cprod(ccce[0][0], q1c, cce[0][0], N);
    cprod(ccce[1][0], q2c, cce[1][0], N);
    cprod(ccce[0][1], q1c, cce[0][1], N);
    cprod(ccce[1][1], q2c, cce[1][1], N);
    cprod(ccce[0][2], q1c, cce[0][2], N);
    cprod(ccce[1][2], q2c, cce[1][2], N);
    cprod(ccce[0][3], q1c, cce[0][3], N);
    cprod(ccce[1][3], q2c, cce[1][3], N);
    cprod(ccce[0][4], q1c, cce[0][4], N);
    cprod(ccce[1][4], q2c, cce[1][4], N);
    cprod(ccce[0][5], q1c, cce[0][5], N);
    cprod(ccce[1][5], q2c, cce[1][5], N);
    cprod(ccce[0][6], yc, cce[0][3], N);
    cprod(ccce[1][6], yc, cce[1][3], N);
    cprod(ccce[0][7], yc, cce[0][4], N);
    cprod(ccce[1][7], yc, cce[1][4], N);
    cprod(ccce[0][8], yc, cce[0][5], N);
    cprod(ccce[1][8], yc, cce[1][5], N);
    cprod(ccce[0][9], zc, cce[0][5], N);
    cprod(ccce[1][9], zc, cce[1][5], N);

    /* 1-coord x f products (3 per body) */
    cprod(cf[0][0], q1c, f1, N);
    cprod(cf[1][0], q2c, f2, N);
    cprod(cf[0][1], yc, f1, N);
    cprod(cf[1][1], yc, f2, N);
    cprod(cf[0][2], zc, f1, N);
    cprod(cf[1][2], zc, f2, N);

    /* 2-coord x f products (6 per body) */
    cprod(ccf[0][0], q1c, cf[0][0], N);
    cprod(ccf[1][0], q2c, cf[1][0], N);
    cprod(ccf[0][1], q1c, cf[0][1], N);
    cprod(ccf[1][1], q2c, cf[1][1], N);
    cprod(ccf[0][2], q1c, cf[0][2], N);
    cprod(ccf[1][2], q2c, cf[1][2], N);
    cprod(ccf[0][3], yc, cf[0][1], N);
    cprod(ccf[1][3], yc, cf[1][1], N);
    cprod(ccf[0][4], yc, cf[0][2], N);
    cprod(ccf[1][4], yc, cf[1][2], N);
    cprod(ccf[0][5], zc, cf[0][2], N);
    cprod(ccf[1][5], zc, cf[1][2], N);

    /* 3-coord x f products (10 per body) */
    cprod(cccf[0][0], q1c, ccf[0][0], N);
    cprod(cccf[1][0], q2c, ccf[1][0], N);
    cprod(cccf[0][1], q1c, ccf[0][1], N);
    cprod(cccf[1][1], q2c, ccf[1][1], N);
    cprod(cccf[0][2], q1c, ccf[0][2], N);
    cprod(cccf[1][2], q2c, ccf[1][2], N);
    cprod(cccf[0][3], q1c, ccf[0][3], N);
    cprod(cccf[1][3], q2c, ccf[1][3], N);
    cprod(cccf[0][4], q1c, ccf[0][4], N);
    cprod(cccf[1][4], q2c, ccf[1][4], N);
    cprod(cccf[0][5], q1c, ccf[0][5], N);
    cprod(cccf[1][5], q2c, ccf[1][5], N);
    cprod(cccf[0][6], yc, ccf[0][3], N);
    cprod(cccf[1][6], yc, ccf[1][3], N);
    cprod(cccf[0][7], yc, ccf[0][4], N);
    cprod(cccf[1][7], yc, ccf[1][4], N);
    cprod(cccf[0][8], yc, ccf[0][5], N);
    cprod(cccf[1][8], yc, ccf[1][5], N);
    cprod(cccf[0][9], zc, ccf[0][5], N);
    cprod(cccf[1][9], zc, ccf[1][5], N);

    /* 4-coord x f products (15 per body) */
    cprod(ccccf[0][0], q1c, cccf[0][0], N);
    cprod(ccccf[1][0], q2c, cccf[1][0], N);
    cprod(ccccf[0][1], q1c, cccf[0][1], N);
    cprod(ccccf[1][1], q2c, cccf[1][1], N);
    cprod(ccccf[0][2], q1c, cccf[0][2], N);
    cprod(ccccf[1][2], q2c, cccf[1][2], N);
    cprod(ccccf[0][3], q1c, cccf[0][3], N);
    cprod(ccccf[1][3], q2c, cccf[1][3], N);
    cprod(ccccf[0][4], q1c, cccf[0][4], N);
    cprod(ccccf[1][4], q2c, cccf[1][4], N);
    cprod(ccccf[0][5], q1c, cccf[0][5], N);
    cprod(ccccf[1][5], q2c, cccf[1][5], N);
    cprod(ccccf[0][6], q1c, cccf[0][6], N);
    cprod(ccccf[1][6], q2c, cccf[1][6], N);
    cprod(ccccf[0][7], q1c, cccf[0][7], N);
    cprod(ccccf[1][7], q2c, cccf[1][7], N);
    cprod(ccccf[0][8], q1c, cccf[0][8], N);
    cprod(ccccf[1][8], q2c, cccf[1][8], N);
    cprod(ccccf[0][9], q1c, cccf[0][9], N);
    cprod(ccccf[1][9], q2c, cccf[1][9], N);
    cprod(ccccf[0][10], yc, cccf[0][6], N);
    cprod(ccccf[1][10], yc, cccf[1][6], N);
    cprod(ccccf[0][11], yc, cccf[0][7], N);
    cprod(ccccf[1][11], yc, cccf[1][7], N);
    cprod(ccccf[0][12], yc, cccf[0][8], N);
    cprod(ccccf[1][12], yc, cccf[1][8], N);
    cprod(ccccf[0][13], yc, cccf[0][9], N);
    cprod(ccccf[1][13], yc, cccf[1][9], N);
    cprod(ccccf[0][14], zc, cccf[0][9], N);
    cprod(ccccf[1][14], zc, cccf[1][9], N);

    /* 1-coord x w products (3 per body) */
    cprod(cw[0][0], q1c, w1, N);
    cprod(cw[1][0], q2c, w2, N);
    cprod(cw[0][1], yc, w1, N);
    cprod(cw[1][1], yc, w2, N);
    cprod(cw[0][2], zc, w1, N);
    cprod(cw[1][2], zc, w2, N);

    /* 2-coord x w products (6 per body) */
    cprod(ccw[0][0], q1c, cw[0][0], N);
    cprod(ccw[1][0], q2c, cw[1][0], N);
    cprod(ccw[0][1], q1c, cw[0][1], N);
    cprod(ccw[1][1], q2c, cw[1][1], N);
    cprod(ccw[0][2], q1c, cw[0][2], N);
    cprod(ccw[1][2], q2c, cw[1][2], N);
    cprod(ccw[0][3], yc, cw[0][1], N);
    cprod(ccw[1][3], yc, cw[1][1], N);
    cprod(ccw[0][4], yc, cw[0][2], N);
    cprod(ccw[1][4], yc, cw[1][2], N);
    cprod(ccw[0][5], zc, cw[0][2], N);
    cprod(ccw[1][5], zc, cw[1][2], N);

    /* 3-coord x w products (10 per body) */
    cprod(cccw[0][0], q1c, ccw[0][0], N);
    cprod(cccw[1][0], q2c, ccw[1][0], N);
    cprod(cccw[0][1], q1c, ccw[0][1], N);
    cprod(cccw[1][1], q2c, ccw[1][1], N);
    cprod(cccw[0][2], q1c, ccw[0][2], N);
    cprod(cccw[1][2], q2c, ccw[1][2], N);
    cprod(cccw[0][3], q1c, ccw[0][3], N);
    cprod(cccw[1][3], q2c, ccw[1][3], N);
    cprod(cccw[0][4], q1c, ccw[0][4], N);
    cprod(cccw[1][4], q2c, ccw[1][4], N);
    cprod(cccw[0][5], q1c, ccw[0][5], N);
    cprod(cccw[1][5], q2c, ccw[1][5], N);
    cprod(cccw[0][6], yc, ccw[0][3], N);
    cprod(cccw[1][6], yc, ccw[1][3], N);
    cprod(cccw[0][7], yc, ccw[0][4], N);
    cprod(cccw[1][7], yc, ccw[1][4], N);
    cprod(cccw[0][8], yc, ccw[0][5], N);
    cprod(cccw[1][8], yc, ccw[1][5], N);
    cprod(cccw[0][9], zc, ccw[0][5], N);
    cprod(cccw[1][9], zc, ccw[1][5], N);

    /* 4-coord x w products (15 per body) */
    cprod(ccccw[0][0], q1c, cccw[0][0], N);
    cprod(ccccw[1][0], q2c, cccw[1][0], N);
    cprod(ccccw[0][1], q1c, cccw[0][1], N);
    cprod(ccccw[1][1], q2c, cccw[1][1], N);
    cprod(ccccw[0][2], q1c, cccw[0][2], N);
    cprod(ccccw[1][2], q2c, cccw[1][2], N);
    cprod(ccccw[0][3], q1c, cccw[0][3], N);
    cprod(ccccw[1][3], q2c, cccw[1][3], N);
    cprod(ccccw[0][4], q1c, cccw[0][4], N);
    cprod(ccccw[1][4], q2c, cccw[1][4], N);
    cprod(ccccw[0][5], q1c, cccw[0][5], N);
    cprod(ccccw[1][5], q2c, cccw[1][5], N);
    cprod(ccccw[0][6], q1c, cccw[0][6], N);
    cprod(ccccw[1][6], q2c, cccw[1][6], N);
    cprod(ccccw[0][7], q1c, cccw[0][7], N);
    cprod(ccccw[1][7], q2c, cccw[1][7], N);
    cprod(ccccw[0][8], q1c, cccw[0][8], N);
    cprod(ccccw[1][8], q2c, cccw[1][8], N);
    cprod(ccccw[0][9], q1c, cccw[0][9], N);
    cprod(ccccw[1][9], q2c, cccw[1][9], N);
    cprod(ccccw[0][10], yc, cccw[0][6], N);
    cprod(ccccw[1][10], yc, cccw[1][6], N);
    cprod(ccccw[0][11], yc, cccw[0][7], N);
    cprod(ccccw[1][11], yc, cccw[1][7], N);
    cprod(ccccw[0][12], yc, cccw[0][8], N);
    cprod(ccccw[1][12], yc, cccw[1][8], N);
    cprod(ccccw[0][13], yc, cccw[0][9], N);
    cprod(ccccw[1][13], yc, cccw[1][9], N);
    cprod(ccccw[0][14], zc, cccw[0][9], N);
    cprod(ccccw[1][14], zc, cccw[1][9], N);

    /* 5-coord x w products (21 per body) */
    cprod(cccccw[0][0], q1c, ccccw[0][0], N);
    cprod(cccccw[1][0], q2c, ccccw[1][0], N);
    cprod(cccccw[0][1], q1c, ccccw[0][1], N);
    cprod(cccccw[1][1], q2c, ccccw[1][1], N);
    cprod(cccccw[0][2], q1c, ccccw[0][2], N);
    cprod(cccccw[1][2], q2c, ccccw[1][2], N);
    cprod(cccccw[0][3], q1c, ccccw[0][3], N);
    cprod(cccccw[1][3], q2c, ccccw[1][3], N);
    cprod(cccccw[0][4], q1c, ccccw[0][4], N);
    cprod(cccccw[1][4], q2c, ccccw[1][4], N);
    cprod(cccccw[0][5], q1c, ccccw[0][5], N);
    cprod(cccccw[1][5], q2c, ccccw[1][5], N);
    cprod(cccccw[0][6], q1c, ccccw[0][6], N);
    cprod(cccccw[1][6], q2c, ccccw[1][6], N);
    cprod(cccccw[0][7], q1c, ccccw[0][7], N);
    cprod(cccccw[1][7], q2c, ccccw[1][7], N);
    cprod(cccccw[0][8], q1c, ccccw[0][8], N);
    cprod(cccccw[1][8], q2c, ccccw[1][8], N);
    cprod(cccccw[0][9], q1c, ccccw[0][9], N);
    cprod(cccccw[1][9], q2c, ccccw[1][9], N);
    cprod(cccccw[0][10], q1c, ccccw[0][10], N);
    cprod(cccccw[1][10], q2c, ccccw[1][10], N);
    cprod(cccccw[0][11], q1c, ccccw[0][11], N);
    cprod(cccccw[1][11], q2c, ccccw[1][11], N);
    cprod(cccccw[0][12], q1c, ccccw[0][12], N);
    cprod(cccccw[1][12], q2c, ccccw[1][12], N);
    cprod(cccccw[0][13], q1c, ccccw[0][13], N);
    cprod(cccccw[1][13], q2c, ccccw[1][13], N);
    cprod(cccccw[0][14], q1c, ccccw[0][14], N);
    cprod(cccccw[1][14], q2c, ccccw[1][14], N);
    cprod(cccccw[0][15], yc, ccccw[0][10], N);
    cprod(cccccw[1][15], yc, ccccw[1][10], N);
    cprod(cccccw[0][16], yc, ccccw[0][11], N);
    cprod(cccccw[1][16], yc, ccccw[1][11], N);
    cprod(cccccw[0][17], yc, ccccw[0][12], N);
    cprod(cccccw[1][17], yc, ccccw[1][12], N);
    cprod(cccccw[0][18], yc, ccccw[0][13], N);
    cprod(cccccw[1][18], yc, ccccw[1][13], N);
    cprod(cccccw[0][19], yc, ccccw[0][14], N);
    cprod(cccccw[1][19], yc, ccccw[1][14], N);
    cprod(cccccw[0][20], zc, ccccw[0][14], N);
    cprod(cccccw[1][20], zc, ccccw[1][14], N);

    /* ================================================================
     * PHASE 3: Build spatial derivative tensors A, B, C, D
     * ================================================================ */

    /* --- A tensor (Jacobian) --- */
    /* A(3+alpha, beta) for alpha,beta in {0,1,2}.
     * Gravitational: -mj*delta(a,b)*g_j + 3*mj*c_a*c_b*h_j (summed over bodies)
     * Centrifugal:   +delta(a,b) for a<2 only (from Omega = (x^2+y^2)/2) */
    for (k = 0; k <= N; k++) {
        for (alpha = 0; alpha < 3; alpha++) {
            for (beta = 0; beta < 3; beta++) {
                double dab = (alpha == beta) ? 1.0 : 0.0;
                /* Centrifugal: +1 at k=0 for (a,b)=(0,0) and (1,1) only */
                double centrifugal = (alpha == beta && alpha < 2 && k == 0) ? 1.0 : 0.0;
                int pidx = PIDX(alpha, beta);
                Atv[alpha][beta][k] = centrifugal
                    + dab * (-mu1*g1[k] - mu*g2[k])
                    + 3.0*mu1*cch[0][pidx][k]
                    + 3.0*mu*cch[1][pidx][k];
            }
        }
    }

    /* --- B tensor (Hessian) --- */
    /* B_j(3+a,b,g) = 3*mj*(d(a,b)*ch_j[g] + d(a,g)*ch_j[b] + d(b,g)*ch_j[a])
     *              - 15*mj * ccce_j[TIDX(a,b,g)] */
    for (k = 0; k <= N; k++) {
        for (alpha = 0; alpha < 3; alpha++) {
            for (beta = 0; beta < 3; beta++) {
                for (gamma = 0; gamma < 3; gamma++) {
                    int bidx = alpha*9 + beta*3 + gamma;
                    int tidx = TIDX(alpha, beta, gamma);
                    double dab = (alpha==beta) ? 1.0 : 0.0;
                    double dag = (alpha==gamma) ? 1.0 : 0.0;
                    double dbg = (beta==gamma) ? 1.0 : 0.0;
                    double val = 0.0;
                    int bd;
                    for (bd = 0; bd < 2; bd++) {
                        double mj = (bd == 0) ? mu1 : mu;
                        val += 3.0*mj*(dab*ch[bd][gamma][k]
                                     + dag*ch[bd][beta][k]
                                     + dbg*ch[bd][alpha][k]);
                        val -= 15.0*mj*ccce[bd][tidx][k];
                    }
                    Bc[bidx][k] = val;
                }
            }
        }
    }

    /* --- C tensor (3rd spatial derivative) --- */
    /* C_j(3+a,b,g,d) = 3*mj*h*(dab*dgd + dag*dbd + dbg*dad)
     *   - 15*mj*(dab*cce[g,d] + dag*cce[b,d] + dbg*cce[a,d]
     *          + dad*cce[b,g] + dbd*cce[a,g] + dgd*cce[a,b])
     *   + 105*mj*ccccf[QIDX(a,b,g,d)] */
    for (k = 0; k <= N; k++) {
        for (alpha = 0; alpha < 3; alpha++) {
            for (beta = 0; beta < 3; beta++) {
                for (gamma = 0; gamma < 3; gamma++) {
                    for (delta = 0; delta < 3; delta++) {
                        int cidx = alpha*27 + beta*9 + gamma*3 + delta;
                        int qidx = QIDX(alpha,beta,gamma,delta);
                        double dab=(alpha==beta)?1.0:0.0, dag=(alpha==gamma)?1.0:0.0;
                        double dbg=(beta==gamma)?1.0:0.0, dad=(alpha==delta)?1.0:0.0;
                        double dbd=(beta==delta)?1.0:0.0, dgd=(gamma==delta)?1.0:0.0;
                        double val = 0.0;
                        int bd;
                        for (bd = 0; bd < 2; bd++) {
                            double mj = (bd == 0) ? mu1 : mu;
                            double hk = (bd == 0) ? h1[k] : h2[k];
                            double hterm = dab*dgd + dag*dbd + dbg*dad;
                            double eterm = dab*cce[bd][PIDX(gamma,delta)][k]
                                + dag*cce[bd][PIDX(beta,delta)][k]
                                + dbg*cce[bd][PIDX(alpha,delta)][k]
                                + dad*cce[bd][PIDX(beta,gamma)][k]
                                + dbd*cce[bd][PIDX(alpha,gamma)][k]
                                + dgd*cce[bd][PIDX(alpha,beta)][k];
                            double fterm = ccccf[bd][qidx][k];
                            val += mj*(3.0*hterm*hk - 15.0*eterm + 105.0*fterm);
                        }
                        Cc[cidx][k] = val;
                    }
                }
            }
        }
    }

    /* --- D tensor (4th spatial derivative) --- */
    /* Uses the factored formula:
     * D_j(3+a,b,g,d,e) = -mj * [
     *   d(a,b)*d3g(g,d,e) + d(a,g)*d3g(b,d,e)
     * + d(a,d)*d3g(b,g,e) + d(a,e)*d3g(b,g,d)
     * + ca * G4(b,g,d,e) ]
     *
     * d3g(i,j,kk) = 15*(d(i,j)*ce[kk] + d(i,kk)*ce[j] + d(j,kk)*ce[i])
     *             - 105*cccf[TIDX(i,j,kk)]
     *
     * ca*G4(b,g,d,e) = 15*(dbg*dde+dbd*dge+dbe*dgd)*ce[a]
     *   - 105*(dbg*cccf[a,d,e] + dbd*cccf[a,g,e] + dbe*cccf[a,g,d]
     *        + dgd*cccf[a,b,e] + dge*cccf[a,b,d] + dde*cccf[a,b,g])
     *   + 945*cccccw[UIDX(a,b,g,d,e)]
     */
    for (k = 0; k <= N; k++) {
        for (alpha = 0; alpha < 3; alpha++) {
            for (beta = 0; beta < 3; beta++) {
                for (gamma = 0; gamma < 3; gamma++) {
                    for (delta = 0; delta < 3; delta++) {
                        for (eps = 0; eps < 3; eps++) {
                            int didx = alpha*81 + beta*27 + gamma*9 + delta*3 + eps;
                            double val = 0.0;
                            int bd;
                            double dab=(alpha==beta)?1.0:0.0, dag=(alpha==gamma)?1.0:0.0;
                            double dad=(alpha==delta)?1.0:0.0, dae=(alpha==eps)?1.0:0.0;
                            double dbg=(beta==gamma)?1.0:0.0, dbd=(beta==delta)?1.0:0.0;
                            double dbe=(beta==eps)?1.0:0.0, dgd=(gamma==delta)?1.0:0.0;
                            double dge=(gamma==eps)?1.0:0.0, dde=(delta==eps)?1.0:0.0;
                            for (bd = 0; bd < 2; bd++) {
                                double mj = (bd == 0) ? mu1 : mu;
                                double d3g_gde, d3g_bde, d3g_bge, d3g_bgd;
                                double caG4;
                                int uidx = UIDX(alpha,beta,gamma,delta,eps);

                                /* d3g(g,d,e) */
                                d3g_gde = 15.0*(dgd*ce[bd][eps][k]
                                    + dge*ce[bd][delta][k]
                                    + dde*ce[bd][gamma][k])
                                    - 105.0*cccf[bd][TIDX(gamma,delta,eps)][k];

                                /* d3g(b,d,e) */
                                d3g_bde = 15.0*(dbd*ce[bd][eps][k]
                                    + dbe*ce[bd][delta][k]
                                    + dde*ce[bd][beta][k])
                                    - 105.0*cccf[bd][TIDX(beta,delta,eps)][k];

                                /* d3g(b,g,e) */
                                d3g_bge = 15.0*(dbg*ce[bd][eps][k]
                                    + dbe*ce[bd][gamma][k]
                                    + dge*ce[bd][beta][k])
                                    - 105.0*cccf[bd][TIDX(beta,gamma,eps)][k];

                                /* d3g(b,g,d) */
                                d3g_bgd = 15.0*(dbg*ce[bd][delta][k]
                                    + dbd*ce[bd][gamma][k]
                                    + dgd*ce[bd][beta][k])
                                    - 105.0*cccf[bd][TIDX(beta,gamma,delta)][k];

                                /* c_alpha * G4(b,g,d,e) */
                                caG4 = 15.0*(dbg*dde + dbd*dge + dbe*dgd)*ce[bd][alpha][k]
                                    - 105.0*(
                                        dbg*cccf[bd][TIDX(alpha,delta,eps)][k]
                                      + dbd*cccf[bd][TIDX(alpha,gamma,eps)][k]
                                      + dbe*cccf[bd][TIDX(alpha,gamma,delta)][k]
                                      + dgd*cccf[bd][TIDX(alpha,beta,eps)][k]
                                      + dge*cccf[bd][TIDX(alpha,beta,delta)][k]
                                      + dde*cccf[bd][TIDX(alpha,beta,gamma)][k])
                                    + 945.0*cccccw[bd][uidx][k];

                                val += -mj * (dab*d3g_gde + dag*d3g_bde
                                            + dad*d3g_bge + dae*d3g_bgd + caG4);
                            }
                            Dc[didx][k] = val;
                        }
                    }
                }
            }
        }
    }

    /* ================================================================
     * PHASE 4: Propagate STT Taylor coefficients
     * ================================================================ */

    /* Zero Phi arrays and set initial conditions */
    memset(P1c, 0, SZ1 * KP1 * sizeof(double));
    memset(P2c, 0, SZ2 * KP1 * sizeof(double));
    memset(P3c, 0, SZ3 * KP1 * sizeof(double));
    memset(P4c, 0, SZ4 * KP1 * sizeof(double));
    memcpy(P1c, Phi1_0, SZ1 * sizeof(double));
    memcpy(P2c, Phi2_0, SZ2 * sizeof(double));
    memcpy(P3c, Phi3_0, SZ3 * sizeof(double));
    memcpy(P4c, Phi4_0, SZ4 * sizeof(double));

    for (k = 0; k < N; k++) {
        inv_kp1 = 1.0 / (double)(k + 1);

        /* ---- Phi1: dPhi1(i,a)/dt = A(i,p)*Phi1(p,a) ---- */

        /* i=0,1,2: constant A entries only (j=0 term) */
        for (a = 0; a < 6; a++) {
            P1c[(k+1)*SZ1 + IDX2(0,a)] = P1c[k*SZ1 + IDX2(3,a)] * inv_kp1;
            P1c[(k+1)*SZ1 + IDX2(1,a)] = P1c[k*SZ1 + IDX2(4,a)] * inv_kp1;
            P1c[(k+1)*SZ1 + IDX2(2,a)] = P1c[k*SZ1 + IDX2(5,a)] * inv_kp1;
        }

        /* i=3,4,5: time-varying A(3+alpha,0..2) + constant velocity coupling */
        for (alpha = 0; alpha < 3; alpha++) {
            i_row = 3 + alpha;
            for (a = 0; a < 6; a++) {
                rhs = 0.0;
                /* Time-varying part: A(i,0..2)*Phi1(0..2,a) Cauchy product */
                for (j = 0; j <= k; j++) {
                    rhs += Atv[alpha][0][j] * P1c[(k-j)*SZ1 + IDX2(0,a)]
                         + Atv[alpha][1][j] * P1c[(k-j)*SZ1 + IDX2(1,a)]
                         + Atv[alpha][2][j] * P1c[(k-j)*SZ1 + IDX2(2,a)];
                }
                /* Constant velocity coupling: A(3,4)=2, A(4,3)=-2, A(5,_)=0 */
                if (alpha == 0) rhs += 2.0 * P1c[k*SZ1 + IDX2(4,a)];
                if (alpha == 1) rhs += -2.0 * P1c[k*SZ1 + IDX2(3,a)];
                P1c[(k+1)*SZ1 + IDX2(i_row,a)] = rhs * inv_kp1;
            }
        }

        /* ---- Phi2: dPhi2(i,a,b)/dt = A(i,p)*Phi2(p,a,b) + B(i,p,q)*Phi1(p,a)*Phi1(q,b) ---- */

        /* i=0,1,2: A*Phi2 only (constant A, no B contribution) */
        for (a = 0; a < 6; a++)
            for (b = 0; b < 6; b++) {
                P2c[(k+1)*SZ2 + IDX3(0,a,b)] = P2c[k*SZ2 + IDX3(3,a,b)] * inv_kp1;
                P2c[(k+1)*SZ2 + IDX3(1,a,b)] = P2c[k*SZ2 + IDX3(4,a,b)] * inv_kp1;
                P2c[(k+1)*SZ2 + IDX3(2,a,b)] = P2c[k*SZ2 + IDX3(5,a,b)] * inv_kp1;
            }

        /* i=3,4,5: A*Phi2 + B*Phi1*Phi1 */
        for (alpha = 0; alpha < 3; alpha++) {
            i_row = 3 + alpha;
            for (a = 0; a < 6; a++) {
                for (b = 0; b < 6; b++) {
                    rhs = 0.0;
                    /* A*Phi2 Cauchy product */
                    for (j = 0; j <= k; j++) {
                        rhs += Atv[alpha][0][j] * P2c[(k-j)*SZ2 + IDX3(0,a,b)]
                             + Atv[alpha][1][j] * P2c[(k-j)*SZ2 + IDX3(1,a,b)]
                             + Atv[alpha][2][j] * P2c[(k-j)*SZ2 + IDX3(2,a,b)];
                    }
                    if (alpha == 0) rhs += 2.0 * P2c[k*SZ2 + IDX3(4,a,b)];
                    if (alpha == 1) rhs += -2.0 * P2c[k*SZ2 + IDX3(3,a,b)];
                    /* B*Phi1*Phi1: p,q restricted to {0,1,2} */
                    for (p = 0; p < 3; p++) {
                        for (q = 0; q < 3; q++) {
                            int bidx = alpha*9 + p*3 + q;
                            for (j1 = 0; j1 <= k; j1++) {
                                double Bv = Bc[bidx][j1];
                                if (Bv == 0.0) continue;
                                for (j2 = 0; j2 <= k-j1; j2++) {
                                    j3 = k - j1 - j2;
                                    rhs += Bv * P1c[j2*SZ1 + IDX2(p,a)]
                                              * P1c[j3*SZ1 + IDX2(q,b)];
                                }
                            }
                        }
                    }
                    P2c[(k+1)*SZ2 + IDX3(i_row,a,b)] = rhs * inv_kp1;
                }
            }
        }

        /* ---- Phi3: dPhi3(i,a,b,c)/dt = A*Phi3 + B*(Phi2*Phi1) + C*Phi1^3 ---- */

        /* i=0,1,2: A*Phi3 only */
        for (a = 0; a < 6; a++)
            for (b = 0; b < 6; b++)
                for (c = 0; c < 6; c++) {
                    P3c[(k+1)*SZ3 + IDX4(0,a,b,c)] = P3c[k*SZ3 + IDX4(3,a,b,c)] * inv_kp1;
                    P3c[(k+1)*SZ3 + IDX4(1,a,b,c)] = P3c[k*SZ3 + IDX4(4,a,b,c)] * inv_kp1;
                    P3c[(k+1)*SZ3 + IDX4(2,a,b,c)] = P3c[k*SZ3 + IDX4(5,a,b,c)] * inv_kp1;
                }

        /* i=3,4,5 */
        for (alpha = 0; alpha < 3; alpha++) {
            i_row = 3 + alpha;
            for (a = 0; a < 6; a++) {
                for (b = 0; b < 6; b++) {
                    for (c = 0; c < 6; c++) {
                        rhs = 0.0;
                        /* A*Phi3 */
                        for (j = 0; j <= k; j++) {
                            rhs += Atv[alpha][0][j] * P3c[(k-j)*SZ3 + IDX4(0,a,b,c)]
                                 + Atv[alpha][1][j] * P3c[(k-j)*SZ3 + IDX4(1,a,b,c)]
                                 + Atv[alpha][2][j] * P3c[(k-j)*SZ3 + IDX4(2,a,b,c)];
                        }
                        if (alpha == 0) rhs += 2.0 * P3c[k*SZ3 + IDX4(4,a,b,c)];
                        if (alpha == 1) rhs += -2.0 * P3c[k*SZ3 + IDX4(3,a,b,c)];
                        /* B*(Phi2*Phi1): 3 permutations, p,q in {0,1,2} */
                        for (p = 0; p < 3; p++) {
                            for (q = 0; q < 3; q++) {
                                int bidx = alpha*9 + p*3 + q;
                                for (j1 = 0; j1 <= k; j1++) {
                                    double Bv = Bc[bidx][j1];
                                    if (Bv == 0.0) continue;
                                    for (j2 = 0; j2 <= k-j1; j2++) {
                                        j3 = k - j1 - j2;
                                        rhs += Bv * (
                                            P2c[j2*SZ2+IDX3(p,a,b)] * P1c[j3*SZ1+IDX2(q,c)]
                                          + P2c[j2*SZ2+IDX3(p,a,c)] * P1c[j3*SZ1+IDX2(q,b)]
                                          + P2c[j2*SZ2+IDX3(p,b,c)] * P1c[j3*SZ1+IDX2(q,a)]);
                                    }
                                }
                            }
                        }
                        /* C*Phi1^3: p,q,r in {0,1,2} */
                        for (p = 0; p < 3; p++) {
                            for (q = 0; q < 3; q++) {
                                for (r = 0; r < 3; r++) {
                                    int cidx = alpha*27 + p*9 + q*3 + r;
                                    for (j1 = 0; j1 <= k; j1++) {
                                        double Cv = Cc[cidx][j1];
                                        if (Cv == 0.0) continue;
                                        for (j2 = 0; j2 <= k-j1; j2++) {
                                            for (j3 = 0; j3 <= k-j1-j2; j3++) {
                                                j4 = k-j1-j2-j3;
                                                rhs += Cv
                                                    * P1c[j2*SZ1+IDX2(p,a)]
                                                    * P1c[j3*SZ1+IDX2(q,b)]
                                                    * P1c[j4*SZ1+IDX2(r,c)];
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        P3c[(k+1)*SZ3 + IDX4(i_row,a,b,c)] = rhs * inv_kp1;
                    }
                }
            }
        }

        /* ---- Phi4: the full variational equation ---- */
        /* dPhi4(i,a,b,c,d)/dt = A*Phi4 + B*(Phi3*Phi1 + Phi2*Phi2)
         *   + C*(Phi2*Phi1^2) + D*Phi1^4 */

        /* i=0,1,2: A*Phi4 only */
        for (a = 0; a < 6; a++)
            for (b = 0; b < 6; b++)
                for (c = 0; c < 6; c++)
                    for (d = 0; d < 6; d++) {
                        P4c[(k+1)*SZ4 + IDX5(0,a,b,c,d)] = P4c[k*SZ4 + IDX5(3,a,b,c,d)] * inv_kp1;
                        P4c[(k+1)*SZ4 + IDX5(1,a,b,c,d)] = P4c[k*SZ4 + IDX5(4,a,b,c,d)] * inv_kp1;
                        P4c[(k+1)*SZ4 + IDX5(2,a,b,c,d)] = P4c[k*SZ4 + IDX5(5,a,b,c,d)] * inv_kp1;
                    }

        /* i=3,4,5 */
        for (alpha = 0; alpha < 3; alpha++) {
            i_row = 3 + alpha;
            for (a = 0; a < 6; a++) {
                for (b = 0; b < 6; b++) {
                    for (c = 0; c < 6; c++) {
                        for (d = 0; d < 6; d++) {
                            rhs = 0.0;
                            /* A*Phi4 */
                            for (j = 0; j <= k; j++) {
                                rhs += Atv[alpha][0][j] * P4c[(k-j)*SZ4 + IDX5(0,a,b,c,d)]
                                     + Atv[alpha][1][j] * P4c[(k-j)*SZ4 + IDX5(1,a,b,c,d)]
                                     + Atv[alpha][2][j] * P4c[(k-j)*SZ4 + IDX5(2,a,b,c,d)];
                            }
                            if (alpha == 0) rhs += 2.0 * P4c[k*SZ4 + IDX5(4,a,b,c,d)];
                            if (alpha == 1) rhs += -2.0 * P4c[k*SZ4 + IDX5(3,a,b,c,d)];
                            /* B terms: p,q in {0,1,2} */
                            for (p = 0; p < 3; p++) {
                                for (q = 0; q < 3; q++) {
                                    int bidx = alpha*9 + p*3 + q;
                                    for (j1 = 0; j1 <= k; j1++) {
                                        double Bv = Bc[bidx][j1];
                                        if (Bv == 0.0) continue;
                                        for (j2 = 0; j2 <= k-j1; j2++) {
                                            j3 = k - j1 - j2;
                                            /* Phi3*Phi1 (4 permutations) */
                                            rhs += Bv * (
                                                P3c[j2*SZ3+IDX4(p,a,b,c)] * P1c[j3*SZ1+IDX2(q,d)]
                                              + P3c[j2*SZ3+IDX4(p,a,b,d)] * P1c[j3*SZ1+IDX2(q,c)]
                                              + P3c[j2*SZ3+IDX4(p,a,c,d)] * P1c[j3*SZ1+IDX2(q,b)]
                                              + P3c[j2*SZ3+IDX4(p,b,c,d)] * P1c[j3*SZ1+IDX2(q,a)]);
                                            /* Phi2*Phi2 (3 permutations) */
                                            rhs += Bv * (
                                                P2c[j2*SZ2+IDX3(p,a,b)] * P2c[j3*SZ2+IDX3(q,c,d)]
                                              + P2c[j2*SZ2+IDX3(p,a,c)] * P2c[j3*SZ2+IDX3(q,b,d)]
                                              + P2c[j2*SZ2+IDX3(p,a,d)] * P2c[j3*SZ2+IDX3(q,b,c)]);
                                        }
                                    }
                                }
                            }
                            /* C terms: p,q,r in {0,1,2} */
                            for (p = 0; p < 3; p++) {
                                for (q = 0; q < 3; q++) {
                                    for (r = 0; r < 3; r++) {
                                        int cidx = alpha*27 + p*9 + q*3 + r;
                                        for (j1 = 0; j1 <= k; j1++) {
                                            double Cv = Cc[cidx][j1];
                                            if (Cv == 0.0) continue;
                                            for (j2 = 0; j2 <= k-j1; j2++) {
                                                for (j3 = 0; j3 <= k-j1-j2; j3++) {
                                                    j4 = k-j1-j2-j3;
                                                    /* 6 Phi2*Phi1^2 permutations */
                                                    rhs += Cv * (
                                                        P2c[j2*SZ2+IDX3(p,a,b)] * P1c[j3*SZ1+IDX2(q,c)] * P1c[j4*SZ1+IDX2(r,d)]
                                                      + P2c[j2*SZ2+IDX3(p,a,c)] * P1c[j3*SZ1+IDX2(q,b)] * P1c[j4*SZ1+IDX2(r,d)]
                                                      + P2c[j2*SZ2+IDX3(p,a,d)] * P1c[j3*SZ1+IDX2(q,b)] * P1c[j4*SZ1+IDX2(r,c)]
                                                      + P2c[j2*SZ2+IDX3(p,b,c)] * P1c[j3*SZ1+IDX2(q,a)] * P1c[j4*SZ1+IDX2(r,d)]
                                                      + P2c[j2*SZ2+IDX3(p,b,d)] * P1c[j3*SZ1+IDX2(q,a)] * P1c[j4*SZ1+IDX2(r,c)]
                                                      + P2c[j2*SZ2+IDX3(p,c,d)] * P1c[j3*SZ1+IDX2(q,a)] * P1c[j4*SZ1+IDX2(r,b)]);
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                            /* D terms: p,q,r,ss in {0,1,2} */
                            for (p = 0; p < 3; p++) {
                                for (q = 0; q < 3; q++) {
                                    for (r = 0; r < 3; r++) {
                                        for (ss = 0; ss < 3; ss++) {
                                            int didx = alpha*81 + p*27 + q*9 + r*3 + ss;
                                            for (j1 = 0; j1 <= k; j1++) {
                                                double Dv = Dc[didx][j1];
                                                if (Dv == 0.0) continue;
                                                for (j2 = 0; j2 <= k-j1; j2++) {
                                                    for (j3 = 0; j3 <= k-j1-j2; j3++) {
                                                        for (j4 = 0; j4 <= k-j1-j2-j3; j4++) {
                                                            int j5 = k-j1-j2-j3-j4;
                                                            rhs += Dv
                                                                * P1c[j2*SZ1+IDX2(p,a)]
                                                                * P1c[j3*SZ1+IDX2(q,b)]
                                                                * P1c[j4*SZ1+IDX2(r,c)]
                                                                * P1c[j5*SZ1+IDX2(ss,d)];
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                            P4c[(k+1)*SZ4 + IDX5(i_row,a,b,c,d)] = rhs * inv_kp1;
                        }
                    }
                }
            }
        }

    } /* end k loop (variational equations) */

    /* ================================================================
     * PHASE 5: Convert Taylor coefficients to raw time derivatives
     *   X^(k) = k! * Xc[k]
     * ================================================================ */

    { int idx;
    for (k = 0; k <= N; k++) {
        double fk = FACT[k];
        Xders[0 + 6*k] = fk * xc[k];
        Xders[1 + 6*k] = fk * yc[k];
        Xders[2 + 6*k] = fk * zc[k];
        Xders[3 + 6*k] = fk * vxc[k];
        Xders[4 + 6*k] = fk * vyc[k];
        Xders[5 + 6*k] = fk * vzc[k];
        for (idx = 0; idx < SZ1; idx++)
            Phi1ders[idx + SZ1*k] = fk * P1c[k*SZ1 + idx];
        for (idx = 0; idx < SZ2; idx++)
            Phi2ders[idx + SZ2*k] = fk * P2c[k*SZ2 + idx];
        for (idx = 0; idx < SZ3; idx++)
            Phi3ders[idx + SZ3*k] = fk * P3c[k*SZ3 + idx];
        for (idx = 0; idx < SZ4; idx++)
            Phi4ders[idx + SZ4*k] = fk * P4c[k*SZ4 + idx];
    }
    }

    return 0;
}
