#!/usr/bin/env python3
"""
generate_cr3bp_stt.py

SymPy-based code generator for CR3BP STT time derivatives.
Produces: cr3bp_stt_time_derivatives_gen.c

This replaces the generic C++ implementation with optimized pure C:
  - No heap allocations (all stack/static arrays)
  - Compact tensor storage (only nonzero B/C/D entries)
  - Sparsity-exploiting variational equation loops
  - Precomputed product tree eliminates 5-fold convolution for D

Usage:
    python3 generate_cr3bp_stt.py
"""

from itertools import combinations_with_replacement
import sys

# =============================================================================
# Sorted-tuple enumeration for coordinate products
# =============================================================================

def enum_tuples(n):
    """Enumerate sorted n-tuples from {0,1,2} with flat index."""
    return list(combinations_with_replacement(range(3), n))

PAIRS   = enum_tuples(2)   # 6 entries
TRIPLES = enum_tuples(3)   # 10 entries
QUADS   = enum_tuples(4)   # 15 entries
QUINTS  = enum_tuples(5)   # 21 entries

def tuple_index(tup):
    """Get flat index for a sorted tuple."""
    n = len(tup)
    table = {2: PAIRS, 3: TRIPLES, 4: QUADS, 5: QUINTS}
    return table[n].index(tuple(sorted(tup)))

def make_lookup_table(n):
    """Generate C lookup table: maps any n-tuple from {0,1,2}^n to sorted flat index."""
    tuples = enum_tuples(n)
    tup_to_idx = {t: i for i, t in enumerate(tuples)}
    # Build full 3^n table
    entries = []
    for idx in range(3**n):
        t = []
        v = idx
        for _ in range(n):
            t.append(v % 3)
            v //= 3
        sorted_t = tuple(sorted(t))
        entries.append(tup_to_idx[sorted_t])
    return entries

# =============================================================================
# Code emission helpers
# =============================================================================

class CodeWriter:
    def __init__(self):
        self.lines = []
        self.indent = 0

    def __call__(self, line=""):
        if line:
            self.lines.append("    " * self.indent + line)
        else:
            self.lines.append("")

    def block(self, header):
        self(header + " {")
        self.indent += 1
        return self

    def end_block(self, suffix=""):
        self.indent -= 1
        self("}" + suffix)

    def text(self):
        return "\n".join(self.lines) + "\n"

# =============================================================================
# Coordinate product name generation
# =============================================================================

COORD_NAMES = ["q", "y", "z"]  # q = q1 or q2 depending on body
POWER_NAMES = {
    "g": "-3/2", "h": "-5/2", "e": "-7/2", "f": "-9/2", "w": "-11/2"
}

def product_varname(body, tup, power):
    """Generate C variable name for a coordinate product × power.
    e.g., body=0, tup=(0,1), power='h' → 'cch1_01'
    """
    prefix = "c" * len(tup)
    suffix = str(body + 1)
    indices = "".join(str(t) for t in tup)
    return f"{prefix}{power}{suffix}_{indices}"

def scalar_power_name(body, power):
    """e.g., body=0, power='h' → 'h1'"""
    return f"{power}{body+1}"

def coord_array_name(body, coord_idx):
    """Return the C variable name for coordinate coord_idx of body."""
    if coord_idx == 0:
        return f"q{body+1}c"
    elif coord_idx == 1:
        return "yc"
    else:
        return "zc"

# =============================================================================
# Generate the C file
# =============================================================================

def generate():
    C = CodeWriter()

    # ---- File header ----
    C("/*" + "=" * 72)
    C(" * cr3bp_stt_time_derivatives_gen.c")
    C(" *")
    C(" * AUTO-GENERATED by generate_cr3bp_stt.py — DO NOT EDIT")
    C(" *")
    C(" * Optimized pure-C implementation of higher-order time derivatives")
    C(" * for the CR3BP state, STM, and 2nd-4th order State Transition Tensors.")
    C(" *")
    C(" * Key optimizations vs. the generic C++ version:")
    C(" *   - No heap allocations (fixed-size stack/static arrays)")
    C(" *   - Compact tensor storage (only nonzero B/C/D entries)")
    C(" *   - Sparsity-exploiting variational equation loops (p,q,r,s < 3)")
    C(" *   - Precomputed product tree eliminates 5-fold convolution for D")
    C(" *")
    C(" * API matches cr3bp_stt_time_derivatives.h")
    C(" * Compile: mex -O cr3bp_stt_time_derivatives_mex.c cr3bp_stt_time_derivatives_gen.c")
    C(" *" + "=" * 72 + "*/")
    C()
    C('#include "cr3bp_stt_time_derivatives.h"')
    C("#include <math.h>")
    C("#include <string.h>")
    C()

    # ---- Constants and macros ----
    C("/* Maximum Taylor coefficients */")
    C("#define KP1 (CR3BP_NMAX + 1)  /* 13 */")
    C()
    C("/* Tensor block sizes */")
    C("#define SZ1  36")
    C("#define SZ2  216")
    C("#define SZ3  1296")
    C("#define SZ4  7776")
    C()
    C("/* Index helpers (0-based, column-major) */")
    C("#define IDX2(i,a) ((i) + 6*(a))")
    C("#define IDX3(i,a,b) ((i) + 6*((a) + 6*(b)))")
    C("#define IDX4(i,a,b,c) ((i) + 6*((a) + 6*((b) + 6*(c))))")
    C("#define IDX5(i,a,b,c,d) ((i) + 6*((a) + 6*((b) + 6*((c) + 6*(d)))))")
    C()

    # ---- Factorial table ----
    C("/* Factorial table */")
    facts = [1.0]
    for i in range(1, 14):
        facts.append(facts[-1] * i)
    fact_str = ", ".join(f"{f:.1f}" for f in facts)
    C(f"static const double FACT[14] = {{{fact_str}}};")
    C()

    # ---- Sorted-tuple lookup tables ----
    for n, name, tuples in [(2, "PAIR", PAIRS), (3, "TRIPLE", TRIPLES),
                             (4, "QUAD", QUADS), (5, "QUINT", QUINTS)]:
        lut = make_lookup_table(n)
        C(f"/* Lookup: any {n}-tuple from {{0,1,2}}^{n} -> sorted flat index (0..{len(tuples)-1}) */")
        C(f"/* Encoding: t[0] + 3*t[1] + 9*t[2] + ... */")
        vals = ", ".join(str(v) for v in lut)
        C(f"static const int {name}_LUT[{3**n}] = {{{vals}}};")
        C()

    # ---- Helper: lookup macros for sorted tuple indices ----
    C("/* Sorted-tuple index lookups */")
    C("#define PIDX(a,b) PAIR_LUT[(a) + 3*(b)]")
    C("#define TIDX(a,b,c) TRIPLE_LUT[(a) + 3*(b) + 9*(c)]")
    C("#define QIDX(a,b,c,d) QUAD_LUT[(a) + 3*(b) + 9*(c) + 27*(d)]")
    C("#define UIDX(a,b,c,d,e) QUINT_LUT[(a) + 3*(b) + 9*(c) + 27*(d) + 81*(e)]")
    C()

    # ---- Static helper functions ----
    C("/* Cauchy product: result[k] = sum_{j=0}^{k} a[j]*b[k-j] for k=0..K */")
    C("static void cprod(double *result, const double *a, const double *b, int K)")
    C("{")
    C("    int kk, jj;")
    C("    for (kk = 0; kk <= K; kk++) {")
    C("        double s = 0.0;")
    C("        for (jj = 0; jj <= kk; jj++)")
    C("            s += a[jj] * b[kk - jj];")
    C("        result[kk] = s;")
    C("    }")
    C("}")
    C()
    C("/* Power recurrence: result = s^alpha as Taylor coefficients */")
    C("static void power_rec(double *result, const double *s, double alpha, int K)")
    C("{")
    C("    int kk, jj;")
    C("    double inv0 = 1.0 / s[0];")
    C("    result[0] = pow(s[0], alpha);")
    C("    for (kk = 1; kk <= K; kk++) {")
    C("        double sum = 0.0;")
    C("        for (jj = 0; jj < kk; jj++)")
    C("            sum += (alpha * (kk - jj) - jj) * s[kk - jj] * result[jj];")
    C("        result[kk] = inv0 * sum / (double)kk;")
    C("    }")
    C("}")
    C()

    # ---- Main function ----
    C("int compute_cr3bp_stt_taylor_coefficients(")
    C("    const double *X0,")
    C("    const double *Phi1_0,")
    C("    const double *Phi2_0,")
    C("    const double *Phi3_0,")
    C("    const double *Phi4_0,")
    C("    double mu,")
    C("    int N,")
    C("    double *Xders,")
    C("    double *Phi1ders,")
    C("    double *Phi2ders,")
    C("    double *Phi3ders,")
    C("    double *Phi4ders)")
    C("{")
    C("    int k, j, j1, j2, j3, j4;")
    C("    int a, b, c, d, alpha, beta, gamma, delta, eps;")
    C("    int p, q, r, ss, i_row;")
    C("    double inv_kp1, rhs, mu1;")
    C()
    C("    if (N < 0 || N > CR3BP_NMAX)")
    C("        return -1;")
    C()
    C("    mu1 = 1.0 - mu;")
    C()

    # ---- Variable declarations ----
    C("    /* ================================================================")
    C("     * ARRAY DECLARATIONS")
    C("     * ================================================================ */")
    C()
    C("    /* State Taylor coefficients */")
    C("    double xc[KP1], yc[KP1], zc[KP1];")
    C("    double vxc[KP1], vyc[KP1], vzc[KP1];")
    C()
    C("    /* Shifted coordinates: q1 = x + mu, q2 = x - 1 + mu */")
    C("    double q1c[KP1], q2c[KP1];")
    C()
    C("    /* Squared terms */")
    C("    double y2[KP1], z2[KP1], q12[KP1], q22[KP1];")
    C()
    C("    /* Squared distances: s1 = q1^2+y^2+z^2, s2 = q2^2+y^2+z^2 */")
    C("    double s1[KP1], s2[KP1];")
    C()

    # Scalar inverse powers
    powers = [("g", "-1.5"), ("h", "-2.5"), ("e", "-3.5"), ("f", "-4.5"), ("w", "-5.5")]
    C("    /* Inverse power scalars: s^alpha */")
    for pname, _ in powers:
        C(f"    double {pname}1[KP1], {pname}2[KP1];")
    C()

    # Coordinate × g (for acceleration, built incrementally)
    C("    /* Coordinate x g products (for acceleration, built incrementally) */")
    C("    double q1g1[KP1], yg1[KP1], zg1[KP1];")
    C("    double q2g2[KP1], yg2[KP1], zg2[KP1];")
    C()

    # Product tree arrays
    # For each power level and tuple length, declare arrays
    # Naming: cp{power}{body}_{tuple}  where c is repeated for tuple length
    # Use indexed arrays: e.g., ch1[3][KP1] for body 1 coord*h, ch2[3][KP1] for body 2
    # Or flat: ch[2][3][KP1]

    # Let me use flat 2D arrays indexed by body and tuple flat index
    product_levels = [
        # (tuple_len, power_letter, needed_for, parent_power_or_tuple)
        (1, "h", "A,B"),
        (2, "h", "A"),
        (1, "e", "B,C,D"),
        (2, "e", "B,C"),
        (3, "e", "B"),
        (1, "f", "C,D"),
        (2, "f", "C,D"),
        (3, "f", "C,D"),
        (4, "f", "C"),
        (1, "w", "D"),
        (2, "w", "D"),
        (3, "w", "D"),
        (4, "w", "D"),
        (5, "w", "D"),
    ]

    C("    /* Coordinate product x inverse-power Taylor series */")
    C("    /* Indexed: [body][flat_tuple_index][taylor_order] */")
    for tlen, pwr, needed in product_levels:
        tuples = enum_tuples(tlen)
        ntup = len(tuples)
        cprefix = "c" * tlen
        C(f"    double {cprefix}{pwr}[2][{ntup}][KP1];  /* {tlen}-coord x {pwr} ({ntup} tuples, for {needed}) */")
    C()

    # A tensor storage (time-varying part only)
    C("    /* A tensor: time-varying entries A(3+alpha, beta) for alpha,beta in {0,1,2} */")
    C("    double Atv[3][3][KP1];")
    C()

    # B, C, D compact storage
    C("    /* B tensor: B(3+alpha, beta, gamma) compact, 27 entries per Taylor order */")
    C("    double Bc[27][KP1];  /* Bc[alpha*9 + beta*3 + gamma][k] */")
    C()
    C("    /* C tensor: C(3+alpha, beta, gamma, delta) compact, 81 entries */")
    C("    double Cc[81][KP1];  /* Cc[alpha*27 + beta*9 + gamma*3 + delta][k] */")
    C()
    C("    /* D tensor: D(3+alpha, beta, gamma, delta, eps) compact, 243 entries */")
    C("    double Dc[243][KP1];")
    C()

    # Phi arrays - static to avoid stack overflow (~970 KB)
    C("    /* Phi Taylor coefficient arrays (static: ~970 KB total) */")
    C("    static double P1c[SZ1 * KP1];")
    C("    static double P2c[SZ2 * KP1];")
    C("    static double P3c[SZ3 * KP1];")
    C("    static double P4c[SZ4 * KP1];")
    C()

    # ================================================================
    # PHASE 1: Build state Taylor coefficients incrementally
    # ================================================================
    C("    /* ================================================================")
    C("     * PHASE 1: Build state Taylor coefficients (incremental)")
    C("     * ================================================================ */")
    C()
    C("    /* Initial conditions */")
    C("    xc[0]  = X0[0]; yc[0]  = X0[1]; zc[0]  = X0[2];")
    C("    vxc[0] = X0[3]; vyc[0] = X0[4]; vzc[0] = X0[5];")
    C()
    C("    /* Build intermediates at k=0 */")
    C("    q1c[0] = xc[0] + mu;")
    C("    q2c[0] = xc[0] - 1.0 + mu;")
    C("    y2[0]  = yc[0] * yc[0];")
    C("    z2[0]  = zc[0] * zc[0];")
    C("    q12[0] = q1c[0] * q1c[0];")
    C("    q22[0] = q2c[0] * q2c[0];")
    C("    s1[0]  = q12[0] + y2[0] + z2[0];")
    C("    s2[0]  = q22[0] + y2[0] + z2[0];")
    C()

    # Power recurrence k=0
    for pname, alpha in powers:
        C(f"    {pname}1[0] = pow(s1[0], {alpha});")
        C(f"    {pname}2[0] = pow(s2[0], {alpha});")
    C()

    # coord*g at k=0
    C("    q1g1[0] = q1c[0] * g1[0];  q2g2[0] = q2c[0] * g2[0];")
    C("    yg1[0]  = yc[0]  * g1[0];  yg2[0]  = yc[0]  * g2[0];")
    C("    zg1[0]  = zc[0]  * g1[0];  zg2[0]  = zc[0]  * g2[0];")
    C()

    # Incremental state build loop
    C("    for (k = 0; k < N; k++) {")
    C("        double axk, ayk, azk;")
    C()
    C("        /* Acceleration Taylor coefficients at order k */")
    C("        axk = 2.0*vyc[k] + xc[k] - mu1*q1g1[k] - mu*q2g2[k];")
    C("        ayk = -2.0*vxc[k] + yc[k] - mu1*yg1[k] - mu*yg2[k];")
    C("        azk = -mu1*zg1[k] - mu*zg2[k];")
    C()
    C("        /* Advance state to order k+1 */")
    C("        inv_kp1 = 1.0 / (double)(k + 1);")
    C("        xc[k+1]  = vxc[k] * inv_kp1;")
    C("        yc[k+1]  = vyc[k] * inv_kp1;")
    C("        zc[k+1]  = vzc[k] * inv_kp1;")
    C("        vxc[k+1] = axk * inv_kp1;")
    C("        vyc[k+1] = ayk * inv_kp1;")
    C("        vzc[k+1] = azk * inv_kp1;")
    C()
    C("        /* Build intermediates at order k+1 */")
    C("        q1c[k+1] = xc[k+1];  /* shift is only at k=0 */")
    C("        q2c[k+1] = xc[k+1];")
    C()
    C("        /* Squares via Cauchy product */")
    C("        { double sy2=0, sz2=0, sq12=0, sq22=0;")
    C("          int jj;")
    C("          for (jj = 0; jj <= k+1; jj++) {")
    C("              sy2  += yc[jj]  * yc[k+1-jj];")
    C("              sz2  += zc[jj]  * zc[k+1-jj];")
    C("              sq12 += q1c[jj] * q1c[k+1-jj];")
    C("              sq22 += q2c[jj] * q2c[k+1-jj];")
    C("          }")
    C("          y2[k+1]  = sy2;  z2[k+1]  = sz2;")
    C("          q12[k+1] = sq12; q22[k+1] = sq22;")
    C("        }")
    C("        s1[k+1] = q12[k+1] + y2[k+1] + z2[k+1];")
    C("        s2[k+1] = q22[k+1] + y2[k+1] + z2[k+1];")
    C()

    # Power recurrence at k+1
    C("        /* Power recurrence at k+1 */")
    C("        { double inv0_1 = 1.0 / s1[0], inv0_2 = 1.0 / s2[0];")
    C("          int kk = k + 1, jj;")
    for pname, alpha in powers:
        C(f"          {{ double sum1=0, sum2=0;")
        C(f"            for (jj = 0; jj < kk; jj++) {{")
        C(f"                double w = {alpha} * (kk - jj) - jj;")
        C(f"                sum1 += w * s1[kk-jj] * {pname}1[jj];")
        C(f"                sum2 += w * s2[kk-jj] * {pname}2[jj];")
        C(f"            }}")
        C(f"            {pname}1[kk] = inv0_1 * sum1 / (double)kk;")
        C(f"            {pname}2[kk] = inv0_2 * sum2 / (double)kk;")
        C(f"          }}")
    C("        }")
    C()

    # coord*g at k+1
    C("        /* coord*g products at k+1 */")
    C("        { double sq1g1=0, sq2g2=0, syg1=0, syg2=0, szg1=0, szg2=0;")
    C("          int jj;")
    C("          for (jj = 0; jj <= k+1; jj++) {")
    C("              sq1g1 += q1c[jj] * g1[k+1-jj];")
    C("              sq2g2 += q2c[jj] * g2[k+1-jj];")
    C("              syg1  += yc[jj]  * g1[k+1-jj];")
    C("              syg2  += yc[jj]  * g2[k+1-jj];")
    C("              szg1  += zc[jj]  * g1[k+1-jj];")
    C("              szg2  += zc[jj]  * g2[k+1-jj];")
    C("          }")
    C("          q1g1[k+1] = sq1g1; q2g2[k+1] = sq2g2;")
    C("          yg1[k+1]  = syg1;  yg2[k+1]  = syg2;")
    C("          zg1[k+1]  = szg1;  zg2[k+1]  = szg2;")
    C("        }")
    C("    } /* end state build loop */")
    C()

    # ================================================================
    # PHASE 2: Build product tree (all orders at once)
    # ================================================================
    C("    /* ================================================================")
    C("     * PHASE 2: Build coordinate-product Taylor series tree")
    C("     * ================================================================ */")
    C()

    # For each product level, emit Cauchy product code
    # The products are built level by level:
    # Level 1: single coord × power
    # Level n: coord × (level n-1 product)

    # We need to track what's been built so we can reference parents
    # Products: indexed as (tuple_len, power_letter) -> array name pattern

    # For level 1: ch[body][coord_idx] = coord × h
    # For level 2: cch[body][pair_idx] = coord_{t[0]} × ch[body][t[1]]
    # For level 3: ccch[body][triple_idx] = coord_{t[0]} × cch[body][pair(t[1],t[2])]
    # etc.

    # Helper: generate code to build all products at one level
    for tlen, pwr, _ in product_levels:
        tuples = enum_tuples(tlen)
        cprefix = "c" * tlen
        arr_name = f"{cprefix}{pwr}"

        C(f"    /* {tlen}-coord x {pwr} products ({len(tuples)} per body) */")

        if tlen == 1:
            # coord × scalar power
            for ti, tup in enumerate(tuples):
                coord_idx = tup[0]
                for body in range(2):
                    coord_var = coord_array_name(body, coord_idx)
                    power_var = f"{pwr}{body+1}"
                    C(f"    cprod({arr_name}[{body}][{ti}], {coord_var}, {power_var}, N);")
        else:
            # coord × (n-1)-level product
            parent_prefix = "c" * (tlen - 1)
            parent_arr = f"{parent_prefix}{pwr}"
            for ti, tup in enumerate(tuples):
                first_coord = tup[0]
                parent_tup = tup[1:]
                parent_tuples = enum_tuples(tlen - 1)
                parent_idx = parent_tuples.index(parent_tup)
                for body in range(2):
                    coord_var = coord_array_name(body, first_coord)
                    C(f"    cprod({arr_name}[{body}][{ti}], {coord_var}, {parent_arr}[{body}][{parent_idx}], N);")
        C()

    # ================================================================
    # PHASE 3: Build A, B, C, D tensors
    # ================================================================
    C("    /* ================================================================")
    C("     * PHASE 3: Build spatial derivative tensors A, B, C, D")
    C("     * ================================================================ */")
    C()

    # --- A tensor ---
    C("    /* --- A tensor (Jacobian) --- */")
    C("    /* A(3+alpha, beta) for alpha,beta in {0,1,2}.")
    C("     * Gravitational: -mj*delta(a,b)*g_j + 3*mj*c_a*c_b*h_j (summed over bodies)")
    C("     * Centrifugal:   +delta(a,b) for a<2 only (from Omega = (x^2+y^2)/2) */")
    C("    for (k = 0; k <= N; k++) {")
    C("        for (alpha = 0; alpha < 3; alpha++) {")
    C("            for (beta = 0; beta < 3; beta++) {")
    C("                double dab = (alpha == beta) ? 1.0 : 0.0;")
    C("                /* Centrifugal: +1 at k=0 for (a,b)=(0,0) and (1,1) only */")
    C("                double centrifugal = (alpha == beta && alpha < 2 && k == 0) ? 1.0 : 0.0;")
    C("                int pidx = PIDX(alpha, beta);")
    C("                Atv[alpha][beta][k] = centrifugal")
    C("                    + dab * (-mu1*g1[k] - mu*g2[k])")
    C("                    + 3.0*mu1*cch[0][pidx][k]")
    C("                    + 3.0*mu*cch[1][pidx][k];")
    C("            }")
    C("        }")
    C("    }")
    C()

    # --- B tensor ---
    C("    /* --- B tensor (Hessian) --- */")
    C("    /* B_j(3+a,b,g) = 3*mj*(d(a,b)*ch_j[g] + d(a,g)*ch_j[b] + d(b,g)*ch_j[a])")
    C("     *              - 15*mj * ccce_j[TIDX(a,b,g)] */")
    C("    for (k = 0; k <= N; k++) {")
    C("        for (alpha = 0; alpha < 3; alpha++) {")
    C("            for (beta = 0; beta < 3; beta++) {")
    C("                for (gamma = 0; gamma < 3; gamma++) {")
    C("                    int bidx = alpha*9 + beta*3 + gamma;")
    C("                    int tidx = TIDX(alpha, beta, gamma);")
    C("                    double dab = (alpha==beta) ? 1.0 : 0.0;")
    C("                    double dag = (alpha==gamma) ? 1.0 : 0.0;")
    C("                    double dbg = (beta==gamma) ? 1.0 : 0.0;")
    C("                    double val = 0.0;")
    C("                    int bd;")
    C("                    for (bd = 0; bd < 2; bd++) {")
    C("                        double mj = (bd == 0) ? mu1 : mu;")
    C("                        val += 3.0*mj*(dab*ch[bd][gamma][k]")
    C("                                     + dag*ch[bd][beta][k]")
    C("                                     + dbg*ch[bd][alpha][k]);")
    C("                        val -= 15.0*mj*ccce[bd][tidx][k];")
    C("                    }")
    C("                    Bc[bidx][k] = val;")
    C("                }")
    C("            }")
    C("        }")
    C("    }")
    C()

    # --- C tensor ---
    C("    /* --- C tensor (3rd spatial derivative) --- */")
    C("    /* C_j(3+a,b,g,d) = 3*mj*h*(dab*dgd + dag*dbd + dbg*dad)")
    C("     *   - 15*mj*(dab*cce[g,d] + dag*cce[b,d] + dbg*cce[a,d]")
    C("     *          + dad*cce[b,g] + dbd*cce[a,g] + dgd*cce[a,b])")
    C("     *   + 105*mj*ccccf[QIDX(a,b,g,d)] */")
    C("    for (k = 0; k <= N; k++) {")
    C("        for (alpha = 0; alpha < 3; alpha++) {")
    C("            for (beta = 0; beta < 3; beta++) {")
    C("                for (gamma = 0; gamma < 3; gamma++) {")
    C("                    for (delta = 0; delta < 3; delta++) {")
    C("                        int cidx = alpha*27 + beta*9 + gamma*3 + delta;")
    C("                        int qidx = QIDX(alpha,beta,gamma,delta);")
    C("                        double dab=(alpha==beta)?1.0:0.0, dag=(alpha==gamma)?1.0:0.0;")
    C("                        double dbg=(beta==gamma)?1.0:0.0, dad=(alpha==delta)?1.0:0.0;")
    C("                        double dbd=(beta==delta)?1.0:0.0, dgd=(gamma==delta)?1.0:0.0;")
    C("                        double val = 0.0;")
    C("                        int bd;")
    C("                        for (bd = 0; bd < 2; bd++) {")
    C("                            double mj = (bd == 0) ? mu1 : mu;")
    C("                            double hk = (bd == 0) ? h1[k] : h2[k];")
    C("                            double hterm = dab*dgd + dag*dbd + dbg*dad;")
    C("                            double eterm = dab*cce[bd][PIDX(gamma,delta)][k]")
    C("                                + dag*cce[bd][PIDX(beta,delta)][k]")
    C("                                + dbg*cce[bd][PIDX(alpha,delta)][k]")
    C("                                + dad*cce[bd][PIDX(beta,gamma)][k]")
    C("                                + dbd*cce[bd][PIDX(alpha,gamma)][k]")
    C("                                + dgd*cce[bd][PIDX(alpha,beta)][k];")
    C("                            double fterm = ccccf[bd][qidx][k];")
    C("                            val += mj*(3.0*hterm*hk - 15.0*eterm + 105.0*fterm);")
    C("                        }")
    C("                        Cc[cidx][k] = val;")
    C("                    }")
    C("                }")
    C("            }")
    C("        }")
    C("    }")
    C()

    # --- D tensor ---
    C("    /* --- D tensor (4th spatial derivative) --- */")
    C("    /* Uses the factored formula:")
    C("     * D_j(3+a,b,g,d,e) = -mj * [")
    C("     *   d(a,b)*d3g(g,d,e) + d(a,g)*d3g(b,d,e)")
    C("     * + d(a,d)*d3g(b,g,e) + d(a,e)*d3g(b,g,d)")
    C("     * + ca * G4(b,g,d,e) ]")
    C("     *")
    C("     * d3g(i,j,kk) = 15*(d(i,j)*ce[kk] + d(i,kk)*ce[j] + d(j,kk)*ce[i])")
    C("     *             - 105*cccf[TIDX(i,j,kk)]")
    C("     *")
    C("     * ca*G4(b,g,d,e) = 15*(dbg*dde+dbd*dge+dbe*dgd)*ce[a]")
    C("     *   - 105*(dbg*cccf[a,d,e] + dbd*cccf[a,g,e] + dbe*cccf[a,g,d]")
    C("     *        + dgd*cccf[a,b,e] + dge*cccf[a,b,d] + dde*cccf[a,b,g])")
    C("     *   + 945*cccccw[UIDX(a,b,g,d,e)]")
    C("     */")
    C("    for (k = 0; k <= N; k++) {")
    C("        for (alpha = 0; alpha < 3; alpha++) {")
    C("            for (beta = 0; beta < 3; beta++) {")
    C("                for (gamma = 0; gamma < 3; gamma++) {")
    C("                    for (delta = 0; delta < 3; delta++) {")
    C("                        for (eps = 0; eps < 3; eps++) {")
    C("                            int didx = alpha*81 + beta*27 + gamma*9 + delta*3 + eps;")
    C("                            double val = 0.0;")
    C("                            int bd;")
    C("                            double dab=(alpha==beta)?1.0:0.0, dag=(alpha==gamma)?1.0:0.0;")
    C("                            double dad=(alpha==delta)?1.0:0.0, dae=(alpha==eps)?1.0:0.0;")
    C("                            double dbg=(beta==gamma)?1.0:0.0, dbd=(beta==delta)?1.0:0.0;")
    C("                            double dbe=(beta==eps)?1.0:0.0, dgd=(gamma==delta)?1.0:0.0;")
    C("                            double dge=(gamma==eps)?1.0:0.0, dde=(delta==eps)?1.0:0.0;")
    C("                            for (bd = 0; bd < 2; bd++) {")
    C("                                double mj = (bd == 0) ? mu1 : mu;")
    C("                                double d3g_gde, d3g_bde, d3g_bge, d3g_bgd;")
    C("                                double caG4;")
    C("                                int uidx = UIDX(alpha,beta,gamma,delta,eps);")
    C()
    C("                                /* d3g(g,d,e) */")
    C("                                d3g_gde = 15.0*(dgd*ce[bd][eps][k]")
    C("                                    + dge*ce[bd][delta][k]")
    C("                                    + dde*ce[bd][gamma][k])")
    C("                                    - 105.0*cccf[bd][TIDX(gamma,delta,eps)][k];")
    C()
    C("                                /* d3g(b,d,e) */")
    C("                                d3g_bde = 15.0*(dbd*ce[bd][eps][k]")
    C("                                    + dbe*ce[bd][delta][k]")
    C("                                    + dde*ce[bd][beta][k])")
    C("                                    - 105.0*cccf[bd][TIDX(beta,delta,eps)][k];")
    C()
    C("                                /* d3g(b,g,e) */")
    C("                                d3g_bge = 15.0*(dbg*ce[bd][eps][k]")
    C("                                    + dbe*ce[bd][gamma][k]")
    C("                                    + dge*ce[bd][beta][k])")
    C("                                    - 105.0*cccf[bd][TIDX(beta,gamma,eps)][k];")
    C()
    C("                                /* d3g(b,g,d) */")
    C("                                d3g_bgd = 15.0*(dbg*ce[bd][delta][k]")
    C("                                    + dbd*ce[bd][gamma][k]")
    C("                                    + dgd*ce[bd][beta][k])")
    C("                                    - 105.0*cccf[bd][TIDX(beta,gamma,delta)][k];")
    C()
    C("                                /* c_alpha * G4(b,g,d,e) */")
    C("                                caG4 = 15.0*(dbg*dde + dbd*dge + dbe*dgd)*ce[bd][alpha][k]")
    C("                                    - 105.0*(")
    C("                                        dbg*cccf[bd][TIDX(alpha,delta,eps)][k]")
    C("                                      + dbd*cccf[bd][TIDX(alpha,gamma,eps)][k]")
    C("                                      + dbe*cccf[bd][TIDX(alpha,gamma,delta)][k]")
    C("                                      + dgd*cccf[bd][TIDX(alpha,beta,eps)][k]")
    C("                                      + dge*cccf[bd][TIDX(alpha,beta,delta)][k]")
    C("                                      + dde*cccf[bd][TIDX(alpha,beta,gamma)][k])")
    C("                                    + 945.0*cccccw[bd][uidx][k];")
    C()
    C("                                val += -mj * (dab*d3g_gde + dag*d3g_bde")
    C("                                            + dad*d3g_bge + dae*d3g_bgd + caG4);")
    C("                            }")
    C("                            Dc[didx][k] = val;")
    C("                        }")
    C("                    }")
    C("                }")
    C("            }")
    C("        }")
    C("    }")
    C()

    # ================================================================
    # PHASE 4: Propagate Phi1, Phi2, Phi3, Phi4
    # ================================================================
    C("    /* ================================================================")
    C("     * PHASE 4: Propagate STT Taylor coefficients")
    C("     * ================================================================ */")
    C()
    C("    /* Zero Phi arrays and set initial conditions */")
    C("    memset(P1c, 0, SZ1 * KP1 * sizeof(double));")
    C("    memset(P2c, 0, SZ2 * KP1 * sizeof(double));")
    C("    memset(P3c, 0, SZ3 * KP1 * sizeof(double));")
    C("    memset(P4c, 0, SZ4 * KP1 * sizeof(double));")
    C("    memcpy(P1c, Phi1_0, SZ1 * sizeof(double));")
    C("    memcpy(P2c, Phi2_0, SZ2 * sizeof(double));")
    C("    memcpy(P3c, Phi3_0, SZ3 * sizeof(double));")
    C("    memcpy(P4c, Phi4_0, SZ4 * sizeof(double));")
    C()

    C("    for (k = 0; k < N; k++) {")
    C("        inv_kp1 = 1.0 / (double)(k + 1);")
    C()

    # ---- Phi1 propagation ----
    C("        /* ---- Phi1: dPhi1(i,a)/dt = A(i,p)*Phi1(p,a) ---- */")
    C()
    C("        /* i=0,1,2: constant A entries only (j=0 term) */")
    C("        for (a = 0; a < 6; a++) {")
    C("            P1c[(k+1)*SZ1 + IDX2(0,a)] = P1c[k*SZ1 + IDX2(3,a)] * inv_kp1;")
    C("            P1c[(k+1)*SZ1 + IDX2(1,a)] = P1c[k*SZ1 + IDX2(4,a)] * inv_kp1;")
    C("            P1c[(k+1)*SZ1 + IDX2(2,a)] = P1c[k*SZ1 + IDX2(5,a)] * inv_kp1;")
    C("        }")
    C()
    C("        /* i=3,4,5: time-varying A(3+alpha,0..2) + constant velocity coupling */")
    C("        for (alpha = 0; alpha < 3; alpha++) {")
    C("            i_row = 3 + alpha;")
    C("            for (a = 0; a < 6; a++) {")
    C("                rhs = 0.0;")
    C("                /* Time-varying part: A(i,0..2)*Phi1(0..2,a) Cauchy product */")
    C("                for (j = 0; j <= k; j++) {")
    C("                    rhs += Atv[alpha][0][j] * P1c[(k-j)*SZ1 + IDX2(0,a)]")
    C("                         + Atv[alpha][1][j] * P1c[(k-j)*SZ1 + IDX2(1,a)]")
    C("                         + Atv[alpha][2][j] * P1c[(k-j)*SZ1 + IDX2(2,a)];")
    C("                }")
    C("                /* Constant velocity coupling: A(3,4)=2, A(4,3)=-2, A(5,_)=0 */")
    C("                if (alpha == 0) rhs += 2.0 * P1c[k*SZ1 + IDX2(4,a)];")
    C("                if (alpha == 1) rhs += -2.0 * P1c[k*SZ1 + IDX2(3,a)];")
    C("                P1c[(k+1)*SZ1 + IDX2(i_row,a)] = rhs * inv_kp1;")
    C("            }")
    C("        }")
    C()

    # ---- Phi2 propagation ----
    C("        /* ---- Phi2: dPhi2(i,a,b)/dt = A(i,p)*Phi2(p,a,b) + B(i,p,q)*Phi1(p,a)*Phi1(q,b) ---- */")
    C()
    C("        /* i=0,1,2: A*Phi2 only (constant A, no B contribution) */")
    C("        for (a = 0; a < 6; a++)")
    C("            for (b = 0; b < 6; b++) {")
    C("                P2c[(k+1)*SZ2 + IDX3(0,a,b)] = P2c[k*SZ2 + IDX3(3,a,b)] * inv_kp1;")
    C("                P2c[(k+1)*SZ2 + IDX3(1,a,b)] = P2c[k*SZ2 + IDX3(4,a,b)] * inv_kp1;")
    C("                P2c[(k+1)*SZ2 + IDX3(2,a,b)] = P2c[k*SZ2 + IDX3(5,a,b)] * inv_kp1;")
    C("            }")
    C()
    C("        /* i=3,4,5: A*Phi2 + B*Phi1*Phi1 */")
    C("        for (alpha = 0; alpha < 3; alpha++) {")
    C("            i_row = 3 + alpha;")
    C("            for (a = 0; a < 6; a++) {")
    C("                for (b = 0; b < 6; b++) {")
    C("                    rhs = 0.0;")
    C("                    /* A*Phi2 Cauchy product */")
    C("                    for (j = 0; j <= k; j++) {")
    C("                        rhs += Atv[alpha][0][j] * P2c[(k-j)*SZ2 + IDX3(0,a,b)]")
    C("                             + Atv[alpha][1][j] * P2c[(k-j)*SZ2 + IDX3(1,a,b)]")
    C("                             + Atv[alpha][2][j] * P2c[(k-j)*SZ2 + IDX3(2,a,b)];")
    C("                    }")
    C("                    if (alpha == 0) rhs += 2.0 * P2c[k*SZ2 + IDX3(4,a,b)];")
    C("                    if (alpha == 1) rhs += -2.0 * P2c[k*SZ2 + IDX3(3,a,b)];")
    C("                    /* B*Phi1*Phi1: p,q restricted to {0,1,2} */")
    C("                    for (p = 0; p < 3; p++) {")
    C("                        for (q = 0; q < 3; q++) {")
    C("                            int bidx = alpha*9 + p*3 + q;")
    C("                            for (j1 = 0; j1 <= k; j1++) {")
    C("                                double Bv = Bc[bidx][j1];")
    C("                                if (Bv == 0.0) continue;")
    C("                                for (j2 = 0; j2 <= k-j1; j2++) {")
    C("                                    j3 = k - j1 - j2;")
    C("                                    rhs += Bv * P1c[j2*SZ1 + IDX2(p,a)]")
    C("                                              * P1c[j3*SZ1 + IDX2(q,b)];")
    C("                                }")
    C("                            }")
    C("                        }")
    C("                    }")
    C("                    P2c[(k+1)*SZ2 + IDX3(i_row,a,b)] = rhs * inv_kp1;")
    C("                }")
    C("            }")
    C("        }")
    C()

    # ---- Phi3 propagation ----
    C("        /* ---- Phi3: dPhi3(i,a,b,c)/dt = A*Phi3 + B*(Phi2*Phi1) + C*Phi1^3 ---- */")
    C()
    C("        /* i=0,1,2: A*Phi3 only */")
    C("        for (a = 0; a < 6; a++)")
    C("            for (b = 0; b < 6; b++)")
    C("                for (c = 0; c < 6; c++) {")
    C("                    P3c[(k+1)*SZ3 + IDX4(0,a,b,c)] = P3c[k*SZ3 + IDX4(3,a,b,c)] * inv_kp1;")
    C("                    P3c[(k+1)*SZ3 + IDX4(1,a,b,c)] = P3c[k*SZ3 + IDX4(4,a,b,c)] * inv_kp1;")
    C("                    P3c[(k+1)*SZ3 + IDX4(2,a,b,c)] = P3c[k*SZ3 + IDX4(5,a,b,c)] * inv_kp1;")
    C("                }")
    C()
    C("        /* i=3,4,5 */")
    C("        for (alpha = 0; alpha < 3; alpha++) {")
    C("            i_row = 3 + alpha;")
    C("            for (a = 0; a < 6; a++) {")
    C("                for (b = 0; b < 6; b++) {")
    C("                    for (c = 0; c < 6; c++) {")
    C("                        rhs = 0.0;")
    C("                        /* A*Phi3 */")
    C("                        for (j = 0; j <= k; j++) {")
    C("                            rhs += Atv[alpha][0][j] * P3c[(k-j)*SZ3 + IDX4(0,a,b,c)]")
    C("                                 + Atv[alpha][1][j] * P3c[(k-j)*SZ3 + IDX4(1,a,b,c)]")
    C("                                 + Atv[alpha][2][j] * P3c[(k-j)*SZ3 + IDX4(2,a,b,c)];")
    C("                        }")
    C("                        if (alpha == 0) rhs += 2.0 * P3c[k*SZ3 + IDX4(4,a,b,c)];")
    C("                        if (alpha == 1) rhs += -2.0 * P3c[k*SZ3 + IDX4(3,a,b,c)];")
    C("                        /* B*(Phi2*Phi1): 3 permutations, p,q in {0,1,2} */")
    C("                        for (p = 0; p < 3; p++) {")
    C("                            for (q = 0; q < 3; q++) {")
    C("                                int bidx = alpha*9 + p*3 + q;")
    C("                                for (j1 = 0; j1 <= k; j1++) {")
    C("                                    double Bv = Bc[bidx][j1];")
    C("                                    if (Bv == 0.0) continue;")
    C("                                    for (j2 = 0; j2 <= k-j1; j2++) {")
    C("                                        j3 = k - j1 - j2;")
    C("                                        rhs += Bv * (")
    C("                                            P2c[j2*SZ2+IDX3(p,a,b)] * P1c[j3*SZ1+IDX2(q,c)]")
    C("                                          + P2c[j2*SZ2+IDX3(p,a,c)] * P1c[j3*SZ1+IDX2(q,b)]")
    C("                                          + P2c[j2*SZ2+IDX3(p,b,c)] * P1c[j3*SZ1+IDX2(q,a)]);")
    C("                                    }")
    C("                                }")
    C("                            }")
    C("                        }")
    C("                        /* C*Phi1^3: p,q,r in {0,1,2} */")
    C("                        for (p = 0; p < 3; p++) {")
    C("                            for (q = 0; q < 3; q++) {")
    C("                                for (r = 0; r < 3; r++) {")
    C("                                    int cidx = alpha*27 + p*9 + q*3 + r;")
    C("                                    for (j1 = 0; j1 <= k; j1++) {")
    C("                                        double Cv = Cc[cidx][j1];")
    C("                                        if (Cv == 0.0) continue;")
    C("                                        for (j2 = 0; j2 <= k-j1; j2++) {")
    C("                                            for (j3 = 0; j3 <= k-j1-j2; j3++) {")
    C("                                                j4 = k-j1-j2-j3;")
    C("                                                rhs += Cv")
    C("                                                    * P1c[j2*SZ1+IDX2(p,a)]")
    C("                                                    * P1c[j3*SZ1+IDX2(q,b)]")
    C("                                                    * P1c[j4*SZ1+IDX2(r,c)];")
    C("                                            }")
    C("                                        }")
    C("                                    }")
    C("                                }")
    C("                            }")
    C("                        }")
    C("                        P3c[(k+1)*SZ3 + IDX4(i_row,a,b,c)] = rhs * inv_kp1;")
    C("                    }")
    C("                }")
    C("            }")
    C("        }")
    C()

    # ---- Phi4 propagation ----
    C("        /* ---- Phi4: the full variational equation ---- */")
    C("        /* dPhi4(i,a,b,c,d)/dt = A*Phi4 + B*(Phi3*Phi1 + Phi2*Phi2)")
    C("         *   + C*(Phi2*Phi1^2) + D*Phi1^4 */")
    C()
    C("        /* i=0,1,2: A*Phi4 only */")
    C("        for (a = 0; a < 6; a++)")
    C("            for (b = 0; b < 6; b++)")
    C("                for (c = 0; c < 6; c++)")
    C("                    for (d = 0; d < 6; d++) {")
    C("                        P4c[(k+1)*SZ4 + IDX5(0,a,b,c,d)] = P4c[k*SZ4 + IDX5(3,a,b,c,d)] * inv_kp1;")
    C("                        P4c[(k+1)*SZ4 + IDX5(1,a,b,c,d)] = P4c[k*SZ4 + IDX5(4,a,b,c,d)] * inv_kp1;")
    C("                        P4c[(k+1)*SZ4 + IDX5(2,a,b,c,d)] = P4c[k*SZ4 + IDX5(5,a,b,c,d)] * inv_kp1;")
    C("                    }")
    C()
    C("        /* i=3,4,5 */")
    C("        for (alpha = 0; alpha < 3; alpha++) {")
    C("            i_row = 3 + alpha;")
    C("            for (a = 0; a < 6; a++) {")
    C("                for (b = 0; b < 6; b++) {")
    C("                    for (c = 0; c < 6; c++) {")
    C("                        for (d = 0; d < 6; d++) {")
    C("                            rhs = 0.0;")
    C("                            /* A*Phi4 */")
    C("                            for (j = 0; j <= k; j++) {")
    C("                                rhs += Atv[alpha][0][j] * P4c[(k-j)*SZ4 + IDX5(0,a,b,c,d)]")
    C("                                     + Atv[alpha][1][j] * P4c[(k-j)*SZ4 + IDX5(1,a,b,c,d)]")
    C("                                     + Atv[alpha][2][j] * P4c[(k-j)*SZ4 + IDX5(2,a,b,c,d)];")
    C("                            }")
    C("                            if (alpha == 0) rhs += 2.0 * P4c[k*SZ4 + IDX5(4,a,b,c,d)];")
    C("                            if (alpha == 1) rhs += -2.0 * P4c[k*SZ4 + IDX5(3,a,b,c,d)];")
    C("                            /* B terms: p,q in {0,1,2} */")
    C("                            for (p = 0; p < 3; p++) {")
    C("                                for (q = 0; q < 3; q++) {")
    C("                                    int bidx = alpha*9 + p*3 + q;")
    C("                                    for (j1 = 0; j1 <= k; j1++) {")
    C("                                        double Bv = Bc[bidx][j1];")
    C("                                        if (Bv == 0.0) continue;")
    C("                                        for (j2 = 0; j2 <= k-j1; j2++) {")
    C("                                            j3 = k - j1 - j2;")
    C("                                            /* Phi3*Phi1 (4 permutations) */")
    C("                                            rhs += Bv * (")
    C("                                                P3c[j2*SZ3+IDX4(p,a,b,c)] * P1c[j3*SZ1+IDX2(q,d)]")
    C("                                              + P3c[j2*SZ3+IDX4(p,a,b,d)] * P1c[j3*SZ1+IDX2(q,c)]")
    C("                                              + P3c[j2*SZ3+IDX4(p,a,c,d)] * P1c[j3*SZ1+IDX2(q,b)]")
    C("                                              + P3c[j2*SZ3+IDX4(p,b,c,d)] * P1c[j3*SZ1+IDX2(q,a)]);")
    C("                                            /* Phi2*Phi2 (3 permutations) */")
    C("                                            rhs += Bv * (")
    C("                                                P2c[j2*SZ2+IDX3(p,a,b)] * P2c[j3*SZ2+IDX3(q,c,d)]")
    C("                                              + P2c[j2*SZ2+IDX3(p,a,c)] * P2c[j3*SZ2+IDX3(q,b,d)]")
    C("                                              + P2c[j2*SZ2+IDX3(p,a,d)] * P2c[j3*SZ2+IDX3(q,b,c)]);")
    C("                                        }")
    C("                                    }")
    C("                                }")
    C("                            }")
    C("                            /* C terms: p,q,r in {0,1,2} */")
    C("                            for (p = 0; p < 3; p++) {")
    C("                                for (q = 0; q < 3; q++) {")
    C("                                    for (r = 0; r < 3; r++) {")
    C("                                        int cidx = alpha*27 + p*9 + q*3 + r;")
    C("                                        for (j1 = 0; j1 <= k; j1++) {")
    C("                                            double Cv = Cc[cidx][j1];")
    C("                                            if (Cv == 0.0) continue;")
    C("                                            for (j2 = 0; j2 <= k-j1; j2++) {")
    C("                                                for (j3 = 0; j3 <= k-j1-j2; j3++) {")
    C("                                                    j4 = k-j1-j2-j3;")
    C("                                                    /* 6 Phi2*Phi1^2 permutations */")
    C("                                                    rhs += Cv * (")
    C("                                                        P2c[j2*SZ2+IDX3(p,a,b)] * P1c[j3*SZ1+IDX2(q,c)] * P1c[j4*SZ1+IDX2(r,d)]")
    C("                                                      + P2c[j2*SZ2+IDX3(p,a,c)] * P1c[j3*SZ1+IDX2(q,b)] * P1c[j4*SZ1+IDX2(r,d)]")
    C("                                                      + P2c[j2*SZ2+IDX3(p,a,d)] * P1c[j3*SZ1+IDX2(q,b)] * P1c[j4*SZ1+IDX2(r,c)]")
    C("                                                      + P2c[j2*SZ2+IDX3(p,b,c)] * P1c[j3*SZ1+IDX2(q,a)] * P1c[j4*SZ1+IDX2(r,d)]")
    C("                                                      + P2c[j2*SZ2+IDX3(p,b,d)] * P1c[j3*SZ1+IDX2(q,a)] * P1c[j4*SZ1+IDX2(r,c)]")
    C("                                                      + P2c[j2*SZ2+IDX3(p,c,d)] * P1c[j3*SZ1+IDX2(q,a)] * P1c[j4*SZ1+IDX2(r,b)]);")
    C("                                                }")
    C("                                            }")
    C("                                        }")
    C("                                    }")
    C("                                }")
    C("                            }")
    C("                            /* D terms: p,q,r,ss in {0,1,2} */")
    C("                            for (p = 0; p < 3; p++) {")
    C("                                for (q = 0; q < 3; q++) {")
    C("                                    for (r = 0; r < 3; r++) {")
    C("                                        for (ss = 0; ss < 3; ss++) {")
    C("                                            int didx = alpha*81 + p*27 + q*9 + r*3 + ss;")
    C("                                            for (j1 = 0; j1 <= k; j1++) {")
    C("                                                double Dv = Dc[didx][j1];")
    C("                                                if (Dv == 0.0) continue;")
    C("                                                for (j2 = 0; j2 <= k-j1; j2++) {")
    C("                                                    for (j3 = 0; j3 <= k-j1-j2; j3++) {")
    C("                                                        for (j4 = 0; j4 <= k-j1-j2-j3; j4++) {")
    C("                                                            int j5 = k-j1-j2-j3-j4;")
    C("                                                            rhs += Dv")
    C("                                                                * P1c[j2*SZ1+IDX2(p,a)]")
    C("                                                                * P1c[j3*SZ1+IDX2(q,b)]")
    C("                                                                * P1c[j4*SZ1+IDX2(r,c)]")
    C("                                                                * P1c[j5*SZ1+IDX2(ss,d)];")
    C("                                                        }")
    C("                                                    }")
    C("                                                }")
    C("                                            }")
    C("                                        }")
    C("                                    }")
    C("                                }")
    C("                            }")
    C("                            P4c[(k+1)*SZ4 + IDX5(i_row,a,b,c,d)] = rhs * inv_kp1;")
    C("                        }")
    C("                    }")
    C("                }")
    C("            }")
    C("        }")
    C()
    C("    } /* end k loop (variational equations) */")
    C()

    # ================================================================
    # PHASE 5: Convert Taylor coefficients to raw derivatives
    # ================================================================
    C("    /* ================================================================")
    C("     * PHASE 5: Convert Taylor coefficients to raw time derivatives")
    C("     *   X^(k) = k! * Xc[k]")
    C("     * ================================================================ */")
    C()
    C("    { int idx;")
    C("    for (k = 0; k <= N; k++) {")
    C("        double fk = FACT[k];")
    C("        Xders[0 + 6*k] = fk * xc[k];")
    C("        Xders[1 + 6*k] = fk * yc[k];")
    C("        Xders[2 + 6*k] = fk * zc[k];")
    C("        Xders[3 + 6*k] = fk * vxc[k];")
    C("        Xders[4 + 6*k] = fk * vyc[k];")
    C("        Xders[5 + 6*k] = fk * vzc[k];")
    C("        for (idx = 0; idx < SZ1; idx++)")
    C("            Phi1ders[idx + SZ1*k] = fk * P1c[k*SZ1 + idx];")
    C("        for (idx = 0; idx < SZ2; idx++)")
    C("            Phi2ders[idx + SZ2*k] = fk * P2c[k*SZ2 + idx];")
    C("        for (idx = 0; idx < SZ3; idx++)")
    C("            Phi3ders[idx + SZ3*k] = fk * P3c[k*SZ3 + idx];")
    C("        for (idx = 0; idx < SZ4; idx++)")
    C("            Phi4ders[idx + SZ4*k] = fk * P4c[k*SZ4 + idx];")
    C("    }")
    C("    }")
    C()
    C("    return 0;")
    C("}")

    return C.text()


if __name__ == "__main__":
    code = generate()
    outfile = "cr3bp_stt_time_derivatives_gen.c"
    with open(outfile, "w") as f:
        f.write(code)
    print(f"Generated {outfile} ({len(code)} bytes, {code.count(chr(10))} lines)")
